// Every preset is just a partial patch of the *global* customize config —
// same shape `pushUpdate` already accepts, so applying one is not a special
// code path, and users can keep fine-tuning individual fields afterwards.
export const QUICK_STYLE_PRESETS = [
  {
    id: 'cute',
    label: 'Cute',
    swatch: '#FF8CC8',
    patch: {
      fontFamily: 'Inter, system-ui, sans-serif',
      textColor: '#3A2233',
      authorColor: '#FF5FA8',
      bubbleBg: 'rgba(255, 235, 246, 0.92)',
      bubbleRadius: 22,
      bubbleOpacity: 1,
      bubbleBorderWidth: 0,
      bubbleBorderStyle: 'none',
      bubbleBoxShadow: '0 4px 14px rgba(255, 140, 200, 0.25)',
      bubbleBunnyEars: true,
    },
  },
  {
    id: 'minimal',
    label: 'Minimal',
    swatch: '#8890A0',
    patch: {
      fontFamily: 'Inter, system-ui, sans-serif',
      textColor: '#EAECEF',
      authorColor: '#EAECEF',
      bubbleBg: 'rgba(22, 25, 31, 0.7)',
      bubbleRadius: 8,
      bubbleOpacity: 1,
      bubbleBorderWidth: 0,
      bubbleBorderStyle: 'none',
      bubbleBoxShadow: 'none',
      bubbleBunnyEars: false,
    },
  },
  {
    id: 'glass',
    label: 'Glass',
    swatch: '#BFEFFF',
    patch: {
      fontFamily: '"Segoe UI", system-ui, sans-serif',
      textColor: '#F4FBFF',
      authorColor: '#BFEFFF',
      bubbleBg: 'rgba(255, 255, 255, 0.12)',
      bubbleRadius: 18,
      bubbleOpacity: 1,
      bubbleBorderWidth: 1,
      bubbleBorderStyle: 'solid',
      bubbleBorderColor: 'rgba(255,255,255,0.4)',
      bubbleBoxShadow: '0 8px 24px rgba(0, 0, 0, 0.25)',
      bubbleBunnyEars: false,
    },
  },
  {
    id: 'dreamcore',
    label: 'Dreamcore',
    swatch: '#C7A7FF',
    patch: {
      fontFamily: '"Space Grotesk", system-ui, sans-serif',
      textColor: '#F1E9FF',
      authorColor: '#C7A7FF',
      bubbleBg: 'rgba(88, 61, 138, 0.55)',
      bubbleRadius: 26,
      bubbleOpacity: 1,
      bubbleBorderWidth: 1,
      bubbleBorderStyle: 'dashed',
      bubbleBorderColor: '#C7A7FF',
      bubbleBoxShadow: '0 8px 24px rgba(120, 80, 200, 0.35)',
      bubbleBunnyEars: true,
    },
  },
  {
    id: 'retro',
    label: 'Retro',
    swatch: '#F5A623',
    patch: {
      fontFamily: 'ui-monospace, "JetBrains Mono", monospace',
      textColor: '#2B1B0E',
      authorColor: '#B8410C',
      bubbleBg: 'rgba(245, 224, 178, 0.95)',
      bubbleRadius: 4,
      bubbleOpacity: 1,
      bubbleBorderWidth: 2,
      bubbleBorderStyle: 'solid',
      bubbleBorderColor: '#2B1B0E',
      bubbleBoxShadow: 'none',
      bubbleBunnyEars: false,
    },
  },
  {
    id: 'neon',
    label: 'Neon',
    swatch: '#35E6B0',
    patch: {
      fontFamily: 'ui-monospace, "JetBrains Mono", monospace',
      textColor: '#EAECEF',
      authorColor: '#35E6B0',
      bubbleBg: 'rgba(14, 16, 19, 0.85)',
      bubbleRadius: 10,
      bubbleOpacity: 1,
      bubbleBorderWidth: 2,
      bubbleBorderStyle: 'solid',
      bubbleBorderColor: '#35E6B0',
      bubbleBoxShadow: '0 0 18px rgba(53, 230, 176, 0.55)',
      bubbleGlow: 'drop-shadow(0 0 6px rgba(53, 230, 176, 0.85)) drop-shadow(0 0 18px rgba(53, 230, 176, 0.55))',
      bubbleBunnyEars: false,
    },
  },
];
