// Theme preset: anime

const { defaultLayout, defaultSlotStyle, emptyDecorations, defaultThemeFanService } = require('../helpers');

module.exports = {
  id: 'anime',
  name: 'Anime',
  author: 'built-in',
  version: '1.1.0',
  description: 'Warm sakura-pink manga-style bubbles, now a soft glass tint with a crisp ink outline — Super Chat gets a full sakura-burst spotlight.',
  category: 'cute',
  tags: ["anime","sakura","manga","pink"],
  createdAt: '2024-01-01',
  modifiedAt: '2026-07-30',
  customizeConfig: {
    fontFamily: '"Segoe UI", system-ui, sans-serif',
    fontSize: 15,
    textAlign: 'left',
    textColor: '#4A2E4E',
    authorColor: '#FF7EC9',
    textGlow: null,
    textStrokeWidth: 0,
    textStrokeColor: null,
    bubbleBg: 'rgba(255, 200, 230, 0.92)',
    bubbleRadius: 22,
    bubbleOpacity: 1,
    bubbleBorderWidth: 1,
    bubbleBorderStyle: 'solid',
    bubbleBorderColor: 'rgba(255, 100, 180, 0.35)',
    bubbleBorderOffset: null,
    bubbleBoxShadow: '0 2px 12px rgba(255, 100, 180, 0.12)',
    bubbleGlow: null,
    bubblePadding: null,
    bubblePaddingX: 14,
    bubblePaddingY: 8,
    bubblePaddingTop: null,
    bubblePaddingRight: null,
    bubblePaddingBottom: null,
    bubblePaddingLeft: null,
    bubbleTextureUrl: null,
    bubbleTextureSize: 'auto',
    bubbleTextureRepeat: 'repeat',
    bubbleTextureOpacity: 1,
    bubbleBunnyEars: false,
    bubbleBunnyEarsWidth: 32,
    bubbleBunnyEarsHeight: 30,
    bubbleBunnyEarsRoundness: 0,
    bubbleBunnyEarsOffsetX: 20,
    bubbleBunnyEarsOffsetY: 28,
    bubbleBunnyEarsRotate: 0,
    bubbleBunnyEarsZIndex: -1,
    bubbleMinWidth: 0,
    bubbleMaxWidth: 0,
    bubbleFixedWidth: 0,
    bubbleMinHeight: 0,
    bubbleMaxHeight: 0,
    bubbleFixedHeight: 0,
    avatarSize: 34,
    showAvatar: true,
    animationMs: 320,
    position: 'bottom-up',
    maxMessages: 40,
    idleAnimation: 'float',
    idleAnimationSpeed: 4.5,
    idleAnimationIntensity: 6.5,
    idleShimmerEnabled: true,
    idleShimmerSpeed: 5,
    idleShimmerIntensity: 4,
    emojiGlyphEnabled: true,
    emojiGlyphBg: 'rgba(255, 255, 255, 0.1)',
    emojiGlyphRadius: 6,
    emojiGlyphOpacity: 1,
    emojiGlyphGlow: null,
  },
  // Manga two-tone speech bubble: solid sakura nameplate band on top,
  // paler glass body underneath — the classic name-tag + dialogue split.
  layoutConfig: defaultLayout({ screen: { headerSplit: true } }),
  slotStyleConfig: defaultSlotStyle({
    slots: {
      author: { bubbleBg: 'rgba(255, 150, 205, 0.95)', color: '#4A2E4E' },
      message: { bubbleBg: 'rgba(255, 235, 246, 0.9)' },
    },
  }),
  animationConfig: {
    enabled: true,
    style: 'bounce',
    targets: {
      avatar:   { durationMs: null, delayMs: 0, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0, translateY: 16, blur: 0 },
      author:   { durationMs: null, delayMs: 40, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: -12, translateY: 0, blur: 0 },
      message:  { durationMs: null, delayMs: 80, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0, translateY: 12, blur: 0 },
    },
  },
  decorationConfig: emptyDecorations(),
  roleStyleConfig: {
    roles: {
      moderator: {
      enabled: true,
      authorColor: '#FF2D78',
      authorBorderColor: 'rgba(255, 45, 120, 0.6)',
      authorBg: null,
      messageBg: 'rgba(255, 161, 202, 0.9)',
      messageBorderColor: 'rgba(255, 45, 120, 0.4)',
      messageTextColor: '#9C1B49',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: null,
      memberTiers: [],
    },
      member: {
      enabled: true,
      authorColor: '#450BCC',
      authorBorderColor: 'rgba(139, 92, 246, 0.55)',
      authorBg: null,
      messageBg: 'rgba(206, 155, 237, 0.92)',
      messageBorderColor: 'rgba(139, 92, 246, 0.4)',
      messageTextColor: '#492D87',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: 1.15,
      memberTiers: [
        { id: 'tier-1mo', minMonths: 1, color: '#450BCC', badge: '🌸' },
        { id: 'tier-3mo', minMonths: 3, color: '#89004F', badge: '🌸🌸' },
        { id: 'tier-6mo', minMonths: 6, color: '#8D0032', badge: '⛩' },
        { id: 'tier-12mo', minMonths: 12, color: '#603D04', badge: '👑' },
      ],
    },
    },
  },
  fanServiceConfig: defaultThemeFanService({
    superchat: { authorColor: '#FF7EC9', messageColor: '#4A2E4E' },
    membership: { authorColor: '#450BCC', messageColor: '#492D87', monthsColor: '#450BCC' },
  }),
};
