// Theme preset: ca-phe

const { defaultLayout, defaultSlotStyle, emptyDecorations, defaultThemeFanService } = require('../helpers');

module.exports = {
  id: 'ca-phe',
  name: 'Cà Phê',
  author: 'built-in',
  version: '1.1.0',
  description: 'Warm coffee-shop tones — cream glass bubble, espresso-brown border, cinnamon accents, gentle steam-like drift, and a rich Super Chat pour.',
  category: 'cozy',
  tags: ["coffee","cozy","brown","cream","warm"],
  createdAt: '2026-07-13',
  modifiedAt: '2026-07-30',
  customizeConfig: {
    fontFamily: '"Nunito", "Merriweather", system-ui, serif',
    fontSize: 15,
    textAlign: 'left',
    textColor: '#4B3324',
    authorColor: '#8B4513',
    textGlow: null,
    textStrokeWidth: 0,
    textStrokeColor: null,
    bubbleBg: 'rgba(245, 232, 216, 0.92)',
    bubbleRadius: 14,
    bubbleOpacity: 1,
    bubbleBorderWidth: 1,
    bubbleBorderStyle: 'solid',
    bubbleBorderColor: 'rgba(93, 64, 55, 0.35)',
    bubbleBorderOffset: null,
    bubbleBoxShadow: '0 3px 12px rgba(75, 51, 36, 0.12)',
    bubbleGlow: null,
    bubblePadding: null,
    bubblePaddingX: null,
    bubblePaddingY: null,
    bubblePaddingTop: null,
    bubblePaddingRight: null,
    bubblePaddingBottom: null,
    bubblePaddingLeft: null,
    bubbleTextureUrl: null,
    bubbleTextureSize: 'auto',
    bubbleTextureRepeat: 'repeat',
    bubbleTextureOpacity: 1,
    bubbleBunnyEars: false,
    bubbleBunnyEarsWidth: 32,
    bubbleBunnyEarsHeight: 30,
    bubbleBunnyEarsRoundness: 0,
    bubbleBunnyEarsOffsetX: 20,
    bubbleBunnyEarsOffsetY: 28,
    bubbleBunnyEarsRotate: 0,
    bubbleBunnyEarsZIndex: -1,
    bubbleMinWidth: 0,
    bubbleMaxWidth: 0,
    bubbleFixedWidth: 0,
    bubbleMinHeight: 0,
    bubbleMaxHeight: 0,
    bubbleFixedHeight: 0,
    avatarSize: 30,
    showAvatar: true,
    animationMs: 260,
    position: 'bottom-up',
    maxMessages: 40,
    idleAnimation: 'float',
    idleAnimationSpeed: 5,
    idleAnimationIntensity: 5.5,
    idleShimmerEnabled: false,
    idleShimmerSpeed: 3,
    idleShimmerIntensity: 5,
    emojiGlyphEnabled: true,
    emojiGlyphBg: 'rgba(255, 255, 255, 0.1)',
    emojiGlyphRadius: 6,
    emojiGlyphOpacity: 1,
    emojiGlyphGlow: null,
  },
  layoutConfig: defaultLayout(),
  slotStyleConfig: defaultSlotStyle(),
  animationConfig: {
    enabled: true,
    style: 'slide',
    targets: {
      avatar:   { durationMs: null, delayMs: 0, easing: 'ease-out', translateX: 0, translateY: 10, blur: 0 },
      author:   { durationMs: null, delayMs: 40, easing: 'ease-out', translateX: -8, translateY: 0, blur: 0 },
      message:  { durationMs: null, delayMs: 80, easing: 'ease-out', translateX: 0, translateY: 8, blur: 0 },
    },
  },
  decorationConfig: emptyDecorations(),
  roleStyleConfig: {
    roles: {
      moderator: {
      enabled: true,
      authorColor: '#6F4E37',
      authorBorderColor: 'rgba(111, 78, 55, 0.65)',
      authorBg: null,
      messageBg: 'rgba(215, 198, 180, 0.9)',
      messageBorderColor: 'rgba(111, 78, 55, 0.4)',
      messageTextColor: '#6F4E37',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: null,
      memberTiers: [],
    },
      member: {
      enabled: true,
      authorColor: '#6D381E',
      authorBorderColor: 'rgba(160, 82, 45, 0.5)',
      authorBg: null,
      messageBg: 'rgba(209, 169, 144, 0.92)',
      messageBorderColor: 'rgba(160, 82, 45, 0.35)',
      messageTextColor: '#68351D',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: '☕',
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: 1.15,
      memberTiers: [
        { id: 'tier-1mo', minMonths: 1, color: '#6D381E', badge: '☕' },
        { id: 'tier-3mo', minMonths: 3, color: '#6F370F', badge: '☕☕' },
        { id: 'tier-6mo', minMonths: 6, color: '#5B402D', badge: '🍂' },
        { id: 'tier-12mo', minMonths: 12, color: '#5D401B', badge: '👑' },
      ],
    },
    },
  },
  fanServiceConfig: defaultThemeFanService({
    superchat: { authorColor: '#8B4513', messageColor: '#4B3324' },
    membership: { authorColor: '#6D381E', messageColor: '#68351D', monthsColor: '#6D381E' },
  }),
};
