/**
 * Theme preset: cute-bubble
 */

const { defaultLayout, defaultSlotStyle, emptyDecorations } = require('../helpers');

module.exports = {
  id: 'cute-bubble',
  name: 'Cute Bubble',
  author: 'built-in',
  version: '1.1.0',
  description: 'Round, colourful speech bubbles with a playful bounce — now a soft glass fill so the fun shape reads without blocking the stream.',
  category: 'cute',
  tags: ["cute","bubble","round","colorful"],
  createdAt: '2024-01-01',
  modifiedAt: '2026-07-30',
  customizeConfig: {
    fontFamily: '"Nunito", "Quicksand", system-ui, sans-serif',
    fontSize: 15,
    textAlign: 'left',
    textColor: '#FFFFFF',
    authorColor: '#FF6FA5',
    textGlow: 'drop-shadow(0 1px 2px rgba(60, 20, 90, 0.7))',
    textStrokeWidth: 0,
    textStrokeColor: null,
    bubbleBg: 'rgba(110, 60, 220, 0.92)',
    bubbleRadius: 999,
    bubbleOpacity: 1,
    bubbleBorderWidth: 2,
    bubbleBorderStyle: 'solid',
    bubbleBorderColor: 'rgba(255, 255, 255, 0.3)',
    bubbleBorderOffset: null,
    bubbleBoxShadow: '0 4px 14px rgba(110, 60, 220, 0.2)',
    bubbleGlow: null,
    bubblePadding: null,
    bubblePaddingX: 18,
    bubblePaddingY: 8,
    bubblePaddingTop: null,
    bubblePaddingRight: null,
    bubblePaddingBottom: null,
    bubblePaddingLeft: null,
    bubbleTextureUrl: null,
    bubbleTextureSize: 'auto',
    bubbleTextureRepeat: 'repeat',
    bubbleTextureOpacity: 1,
    bubbleBunnyEars: false,
    bubbleBunnyEarsWidth: 32,
    bubbleBunnyEarsHeight: 30,
    bubbleBunnyEarsRoundness: 0,
    bubbleBunnyEarsOffsetX: 20,
    bubbleBunnyEarsOffsetY: 28,
    bubbleBunnyEarsRotate: 0,
    bubbleBunnyEarsZIndex: -1,
    bubbleMinWidth: 0,
    bubbleMaxWidth: 0,
    bubbleFixedWidth: 0,
    bubbleMinHeight: 0,
    bubbleMaxHeight: 0,
    bubbleFixedHeight: 0,
    avatarSize: 34,
    showAvatar: true,
    showBadges: false,
    animationMs: 300,
    position: 'bottom-up',
    maxMessages: 35,
    idleAnimation: 'float',
    idleAnimationSpeed: 3.5,
    idleAnimationIntensity: 8,
    idleShimmerEnabled: true,
    idleShimmerSpeed: 4,
    idleShimmerIntensity: 5,
    emojiGlyphEnabled: true,
    emojiGlyphBg: 'rgba(255, 255, 255, 0.1)',
    emojiGlyphRadius: 6,
    emojiGlyphOpacity: 1,
    emojiGlyphGlow: null,
  },
  layoutConfig: defaultLayout(),
  slotStyleConfig: defaultSlotStyle(),
  animationConfig: {
    enabled: true,
    style: 'bounce',
    targets: {
      avatar:   { durationMs: null, delayMs: 0, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0, translateY: 16, blur: 0 },
      author:   { durationMs: null, delayMs: 40, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: -12, translateY: 0, blur: 0 },
      badges:   { durationMs: null, delayMs: 60, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: -8, translateY: 0, blur: 0 },
      message:  { durationMs: null, delayMs: 80, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0, translateY: 12, blur: 0 },
    },
  },
  decorationConfig: emptyDecorations(),
  roleStyleConfig: {
    roles: {
      moderator: {
      enabled: true,
      authorColor: '#FF4081',
      authorBorderColor: 'rgba(255, 64, 129, 0.6)',
      authorBg: null,
      messageBg: 'rgba(255, 64, 129, 0.9)',
      messageBorderColor: 'rgba(255, 64, 129, 0.45)',
      messageTextColor: '#5E1830',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      showAmount: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: null,
      memberTiers: [],
    },
      member: {
      // Renewal ("Gia hạn") stand-out layout — glowing bubble, not the
      // two-tier YouTube card, so it reads as "special" without breaking
      // the theme's own bubble silhouette.
      milestoneLayout: 'highlight',
      enabled: true,
      authorColor: '#052D19',
      authorBorderColor: 'rgba(105, 240, 174, 0.55)',
      authorBg: null,
      messageBg: 'rgba(108, 136, 201, 0.92)',
      messageBorderColor: 'rgba(105, 240, 174, 0.4)',
      messageTextColor: '#042314',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      showAmount: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: 1.15,
      memberTiers: [
        { id: 'tier-1mo', minMonths: 1, color: '#052D19', badge: '🍬' },
        { id: 'tier-3mo', minMonths: 3, color: '#002A3C', badge: '🍬🍬' },
        { id: 'tier-6mo', minMonths: 6, color: '#54001E', badge: '🎈' },
        { id: 'tier-12mo', minMonths: 12, color: '#2B2700', badge: '👑' },
      ],
    },
      superchat: {
      enabled: true,
      authorColor: '#FFEB3B',
      authorBorderColor: 'rgba(255, 235, 59, 0.6)',
      authorBg: null,
      messageBg: 'rgba(255, 235, 59, 0.92)',
      messageBorderColor: 'rgba(255, 235, 59, 0.5)',
      messageTextColor: '#786E1C',
      rowBg: 'rgba(255, 235, 59, 0.92)',
      rowBorderColor: 'rgba(255, 235, 59, 0.5)',
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      showAmount: true,
      fontSize: null,
      authorFontWeight: null,
      messageBorderWidth: 2,
      textScale: 1.3,
      memberTiers: [],
      useTierColor: false,
      superchatLayout: 'youtube',
      amountFontSize: null,
      amountFontWeight: 'extrabold',
      amountPosition: 'block',
    },
    },
  },
};
