// Theme preset: cute

const { defaultLayout, defaultSlotStyle, emptyDecorations, defaultThemeFanService } = require('../helpers');

module.exports = {
  id: 'cute',
  name: 'Cute',
  author: 'built-in',
  version: '1.1.0',
  description: 'Warm pink glass bubbles with round edges and bunny ears — cosy and kawaii, light on the eyes, with a bigger spotlight for Super Chat.',
  category: 'cute',
  tags: ["cute","pink","kawaii","bunny"],
  createdAt: '2024-01-01',
  modifiedAt: '2026-07-30',
  customizeConfig: {
    fontFamily: 'Inter, system-ui, sans-serif',
    fontSize: 16,
    textAlign: 'left',
    textColor: '#3A2233',
    authorColor: '#FF5FA8',
    textGlow: null,
    textStrokeWidth: 0,
    textStrokeColor: null,
    bubbleBg: 'rgba(255, 235, 246, 0.92)',
    bubbleRadius: 22,
    bubbleOpacity: 1,
    bubbleBorderWidth: 1,
    bubbleBorderStyle: 'solid',
    bubbleBorderColor: 'rgba(255, 95, 168, 0.25)',
    bubbleBorderOffset: null,
    bubbleBoxShadow: '0 4px 14px rgba(255, 140, 200, 0.15)',
    bubbleGlow: null,
    bubblePadding: null,
    bubblePaddingX: null,
    bubblePaddingY: null,
    bubblePaddingTop: null,
    bubblePaddingRight: null,
    bubblePaddingBottom: null,
    bubblePaddingLeft: null,
    bubbleTextureUrl: null,
    bubbleTextureSize: 'auto',
    bubbleTextureRepeat: 'repeat',
    bubbleTextureOpacity: 1,
    bubbleBunnyEars: true,
    bubbleBunnyEarsWidth: 32,
    bubbleBunnyEarsHeight: 30,
    bubbleBunnyEarsRoundness: 0,
    bubbleBunnyEarsOffsetX: 20,
    bubbleBunnyEarsOffsetY: 28,
    bubbleBunnyEarsRotate: 0,
    bubbleBunnyEarsZIndex: -1,
    bubbleMinWidth: 0,
    bubbleMaxWidth: 0,
    bubbleFixedWidth: 0,
    bubbleMinHeight: 0,
    bubbleMaxHeight: 0,
    bubbleFixedHeight: 0,
    avatarSize: 32,
    showAvatar: true,
    animationMs: 220,
    position: 'bottom-up',
    maxMessages: 40,
    idleAnimation: 'float',
    idleAnimationSpeed: 4,
    idleAnimationIntensity: 6.5,
    idleShimmerEnabled: true,
    idleShimmerSpeed: 4.5,
    idleShimmerIntensity: 4,
    emojiGlyphEnabled: true,
    emojiGlyphBg: 'rgba(255, 255, 255, 0.1)',
    emojiGlyphRadius: 6,
    emojiGlyphOpacity: 1,
    emojiGlyphGlow: null,
  },
  // Sticker-style name tag — a light kawaii tilt on the author bubble only.
  layoutConfig: defaultLayout(),
  slotStyleConfig: defaultSlotStyle({
    slots: { author: { rotate: -4, translateY: -2, zIndex: 2 } },
  }),
  animationConfig: {
    enabled: true,
    style: 'slide',
    targets: {
      avatar:   { durationMs: null, delayMs: 0, easing: 'ease-out', translateX: 0, translateY: 8, blur: 0 },
      author:   { durationMs: null, delayMs: 40, easing: 'ease-out', translateX: -6, translateY: 0, blur: 0 },
      message:  { durationMs: null, delayMs: 80, easing: 'ease-out', translateX: 0, translateY: 6, blur: 0 },
    },
  },
  decorationConfig: emptyDecorations(),
  roleStyleConfig: {
    roles: {
      moderator: {
      enabled: true,
      authorColor: '#E91E8C',
      authorBorderColor: 'rgba(233, 30, 140, 0.6)',
      authorBg: null,
      messageBg: 'rgba(251, 200, 228, 0.9)',
      messageBorderColor: 'rgba(233, 30, 140, 0.35)',
      messageTextColor: '#B8186F',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: null,
      memberTiers: [],
    },
      member: {
      enabled: true,
      authorColor: '#683D71',
      authorBorderColor: 'rgba(156, 95, 168, 0.5)',
      authorBg: null,
      messageBg: 'rgba(213, 176, 213, 0.92)',
      messageBorderColor: 'rgba(156, 95, 168, 0.35)',
      messageTextColor: '#613B68',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: 1.15,
      memberTiers: [
        { id: 'tier-1mo', minMonths: 1, color: '#683D71', badge: '🐰' },
        { id: 'tier-3mo', minMonths: 3, color: '#9B0047', badge: '🐰🐰' },
        { id: 'tier-6mo', minMonths: 6, color: '#7B3C06', badge: '🎀' },
        { id: 'tier-12mo', minMonths: 12, color: '#5A4D00', badge: '👑' },
      ],
    },
    },
  },
  fanServiceConfig: defaultThemeFanService({
    superchat: { authorColor: '#FF5FA8', messageColor: '#3A2233' },
    membership: { authorColor: '#683D71', messageColor: '#613B68', monthsColor: '#683D71' },
  }),
};
