// Theme preset: default

const { defaultLayout, defaultSlotStyle, emptyDecorations, defaultThemeFanService } = require('../helpers');

module.exports = {
  id: 'default',
  name: 'Default',
  author: 'built-in',
  version: '1.1.0',
  description: 'The standard dark-panel look shipped with YouTube Overlay Studio — now glass-transparent with clear Super Chat/Membership emphasis.',
  category: 'dark',
  tags: ["dark","clean","default"],
  createdAt: '2024-01-01',
  modifiedAt: '2026-07-30',
  customizeConfig: {
    fontFamily: 'Inter, system-ui, sans-serif',
    fontSize: 16,
    textAlign: 'left',
    textColor: '#EAECEF',
    authorColor: '#8B7CF6',
    textGlow: 'drop-shadow(0 1px 3px rgba(0, 0, 0, 0.85))',
    textStrokeWidth: 0,
    textStrokeColor: null,
    bubbleBg: 'rgba(18, 20, 26, 0.92)',
    bubbleRadius: 14,
    bubbleOpacity: 1,
    bubbleBorderWidth: 1,
    bubbleBorderStyle: 'solid',
    bubbleBorderColor: 'rgba(255, 255, 255, 0.10)',
    bubbleBorderOffset: null,
    bubbleBoxShadow: '0 2px 10px rgba(0, 0, 0, 0.25)',
    bubbleGlow: null,
    bubblePadding: null,
    bubblePaddingX: null,
    bubblePaddingY: null,
    bubblePaddingTop: null,
    bubblePaddingRight: null,
    bubblePaddingBottom: null,
    bubblePaddingLeft: null,
    bubbleTextureUrl: null,
    bubbleTextureSize: 'auto',
    bubbleTextureRepeat: 'repeat',
    bubbleTextureOpacity: 1,
    bubbleBunnyEars: false,
    bubbleBunnyEarsWidth: 32,
    bubbleBunnyEarsHeight: 30,
    bubbleBunnyEarsRoundness: 0,
    bubbleBunnyEarsOffsetX: 20,
    bubbleBunnyEarsOffsetY: 28,
    bubbleBunnyEarsRotate: 0,
    bubbleBunnyEarsZIndex: -1,
    bubbleMinWidth: 0,
    bubbleMaxWidth: 0,
    bubbleFixedWidth: 0,
    bubbleMinHeight: 0,
    bubbleMaxHeight: 0,
    bubbleFixedHeight: 0,
    avatarSize: 32,
    showAvatar: true,
    animationMs: 220,
    position: 'bottom-up',
    maxMessages: 40,
    idleAnimation: 'float',
    idleAnimationSpeed: 5,
    idleAnimationIntensity: 5.5,
    idleShimmerEnabled: false,
    idleShimmerSpeed: 3,
    idleShimmerIntensity: 5,
    emojiGlyphEnabled: true,
    emojiGlyphBg: 'rgba(255, 255, 255, 0.1)',
    emojiGlyphRadius: 6,
    emojiGlyphOpacity: 1,
    emojiGlyphGlow: null,
  },
  layoutConfig: defaultLayout(),
  slotStyleConfig: defaultSlotStyle(),
  animationConfig: {
    enabled: true,
    style: 'slide',
    targets: {
      avatar:   { durationMs: null, delayMs: 0, easing: 'ease-out', translateX: 0, translateY: 8, blur: 0 },
      author:   { durationMs: null, delayMs: 40, easing: 'ease-out', translateX: -6, translateY: 0, blur: 0 },
      message:  { durationMs: null, delayMs: 80, easing: 'ease-out', translateX: 0, translateY: 6, blur: 0 },
    },
  },
  decorationConfig: emptyDecorations(),
  roleStyleConfig: {
    roles: {
      moderator: {
      enabled: true,
      authorColor: '#fca5a5',
      authorBorderColor: 'rgba(248, 113, 113, 0.7)',
      authorBg: null,
      messageBg: 'rgba(86, 50, 54, 0.9)',
      messageBorderColor: 'rgba(248, 113, 113, 0.45)',
      messageTextColor: '#fca5a5',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: null,
      memberTiers: [],
    },
      member: {
      enabled: true,
      authorColor: '#93c5fd',
      authorBorderColor: 'rgba(96, 165, 250, 0.55)',
      authorBg: null,
      messageBg: 'rgba(72, 94, 121, 0.92)',
      messageBorderColor: 'rgba(96, 165, 250, 0.45)',
      messageTextColor: '#BBDBFE',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: 1.15,
      memberTiers: [
        { id: 'tier-1mo', minMonths: 1, color: '#93c5fd', badge: null },
        { id: 'tier-3mo', minMonths: 3, color: '#8DBFFB', badge: null },
        { id: 'tier-6mo', minMonths: 6, color: '#97BDFA', badge: null },
        { id: 'tier-12mo', minMonths: 12, color: '#facc15', badge: '👑' },
      ],
    },
    },
  },
  fanServiceConfig: defaultThemeFanService({
    superchat: { authorColor: '#8B7CF6', messageColor: '#EAECEF' },
    membership: { authorColor: '#93c5fd', messageColor: '#BBDBFE', monthsColor: '#93c5fd' },
  }),
};
