/**
 * Theme preset: discord
 */

const { defaultLayout, defaultSlotStyle, emptyDecorations } = require('../helpers');

module.exports = {
  id: 'discord',
  name: 'Discord',
  author: 'built-in',
  version: '1.1.0',
  description: 'Familiar Discord-style glass panel with Blurple accents — quiet as normal chat, but Nitro-worthy for Super Chat.',
  category: 'dark',
  tags: ["dark","discord","blurple"],
  createdAt: '2024-01-01',
  modifiedAt: '2026-07-30',
  customizeConfig: {
    fontFamily: '"Whitney", "Helvetica Neue", Helvetica, Arial, sans-serif',
    fontSize: 15,
    textAlign: 'left',
    textColor: '#DCDDDE',
    authorColor: '#7289DA',
    textGlow: 'drop-shadow(0 1px 2px rgba(0, 0, 0, 0.75))',
    textStrokeWidth: 0,
    textStrokeColor: null,
    bubbleBg: 'rgba(47, 49, 54, 0.92)',
    bubbleRadius: 8,
    bubbleOpacity: 1,
    bubbleBorderWidth: 1,
    bubbleBorderStyle: 'solid',
    bubbleBorderColor: 'rgba(114, 137, 218, 0.12)',
    bubbleBorderOffset: null,
    bubbleBoxShadow: null,
    bubbleGlow: null,
    bubblePadding: null,
    bubblePaddingX: 14,
    bubblePaddingY: 8,
    bubblePaddingTop: null,
    bubblePaddingRight: null,
    bubblePaddingBottom: null,
    bubblePaddingLeft: null,
    bubbleTextureUrl: null,
    bubbleTextureSize: 'auto',
    bubbleTextureRepeat: 'repeat',
    bubbleTextureOpacity: 1,
    bubbleBunnyEars: false,
    bubbleBunnyEarsWidth: 32,
    bubbleBunnyEarsHeight: 30,
    bubbleBunnyEarsRoundness: 0,
    bubbleBunnyEarsOffsetX: 20,
    bubbleBunnyEarsOffsetY: 28,
    bubbleBunnyEarsRotate: 0,
    bubbleBunnyEarsZIndex: -1,
    bubbleMinWidth: 0,
    bubbleMaxWidth: 0,
    bubbleFixedWidth: 0,
    bubbleMinHeight: 0,
    bubbleMaxHeight: 0,
    bubbleFixedHeight: 0,
    avatarSize: 36,
    showAvatar: true,
    showBadges: false,
    animationMs: 180,
    position: 'bottom-up',
    maxMessages: 35,
    idleAnimation: 'float',
    idleAnimationSpeed: 5.5,
    idleAnimationIntensity: 5.5,
    idleShimmerEnabled: false,
    idleShimmerSpeed: 3,
    idleShimmerIntensity: 5,
    emojiGlyphEnabled: true,
    emojiGlyphBg: 'rgba(255, 255, 255, 0.1)',
    emojiGlyphRadius: 6,
    emojiGlyphOpacity: 1,
    emojiGlyphGlow: null,
  },
  layoutConfig: defaultLayout(),
  slotStyleConfig: defaultSlotStyle(),
  animationConfig: {
    enabled: true,
    style: 'slide',
    targets: {
      avatar:   { durationMs: null, delayMs: 0, easing: 'ease-out', translateX: 0, translateY: 8, blur: 0 },
      author:   { durationMs: null, delayMs: 40, easing: 'ease-out', translateX: -6, translateY: 0, blur: 0 },
      badges:   { durationMs: null, delayMs: 60, easing: 'ease-out', translateX: -4, translateY: 0, blur: 0 },
      message:  { durationMs: null, delayMs: 80, easing: 'ease-out', translateX: 0, translateY: 6, blur: 0 },
    },
  },
  decorationConfig: emptyDecorations(),
  roleStyleConfig: {
    roles: {
      moderator: {
      enabled: true,
      authorColor: '#43B581',
      authorBorderColor: 'rgba(67, 181, 129, 0.6)',
      authorBg: null,
      messageBg: 'rgba(50, 71, 66, 0.9)',
      messageBorderColor: 'rgba(67, 181, 129, 0.4)',
      messageTextColor: '#54BC8C',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      showAmount: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: null,
      memberTiers: [],
    },
      member: {
      // Renewal ("Gia hạn") stand-out layout — glowing bubble, not the
      // two-tier YouTube card, so it reads as "special" without breaking
      // the theme's own bubble silhouette.
      milestoneLayout: 'highlight',
      enabled: true,
      authorColor: '#A4B3E8',
      authorBorderColor: 'rgba(114, 137, 218, 0.55)',
      authorBg: null,
      messageBg: 'rgba(75, 86, 123, 0.92)',
      messageBorderColor: 'rgba(114, 137, 218, 0.4)',
      messageTextColor: '#C5CEF0',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      showAmount: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: 1.15,
      memberTiers: [
        { id: 'tier-1mo', minMonths: 1, color: '#A4B3E8', badge: null },
        { id: 'tier-3mo', minMonths: 3, color: '#A9AFF8', badge: null },
        { id: 'tier-6mo', minMonths: 6, color: '#F498C9', badge: null },
        { id: 'tier-12mo', minMonths: 12, color: '#FEE75C', badge: '👑' },
      ],
    },
      superchat: {
      enabled: true,
      authorColor: '#FEE75C',
      authorBorderColor: 'rgba(254, 231, 92, 0.6)',
      authorBg: null,
      messageBg: 'rgba(78, 68, 30, 0.92)',
      messageBorderColor: 'rgba(254, 231, 92, 0.5)',
      messageTextColor: '#FEE75C',
      rowBg: 'rgba(78, 68, 30, 0.92)',
      rowBorderColor: 'rgba(254, 231, 92, 0.5)',
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      showAmount: true,
      fontSize: null,
      authorFontWeight: null,
      messageBorderWidth: 2,
      textScale: 1.3,
      memberTiers: [],
      useTierColor: true,
      superchatLayout: 'youtube',
      amountFontSize: null,
      amountFontWeight: 'extrabold',
      amountPosition: 'block',
    },
    },
  },
};
