// Theme preset: edgy

const { defaultLayout, defaultSlotStyle, emptyDecorations, defaultThemeFanService } = require('../helpers');

module.exports = {
  id: 'edgy',
  name: 'Edgy',
  author: 'built-in',
  version: '1.0.0',
  description: 'Song hành hai mặt thiện–ác: viền vàng hào quang thánh thần cháy lên trên nền đen tuyền, ánh đỏ quỷ dữ rực ở góc bo cực gắt — một khí chất "edgy" vừa thiêng liêng vừa quỷ ám.',
  category: 'dark',
  tags: ["edgy","saint","demon","gothic","dark","gold","crimson"],
  createdAt: '2026-07-31',
  modifiedAt: '2026-07-31',
  customizeConfig: {
    fontFamily: '"Cinzel", "Playfair Display", Georgia, serif',
    fontSize: 17,
    textAlign: 'left',
    textColor: '#EDE6DA',
    authorColor: '#D4AF37',
    textGlow: 'drop-shadow(0 0 3px rgba(212, 175, 55, 0.45)) drop-shadow(0 0 7px rgba(196, 16, 47, 0.35))',
    textStrokeWidth: 0,
    textStrokeColor: null,
    bubbleBg: 'rgba(10, 8, 10, 0.94)',
    bubbleRadius: 4,
    bubbleOpacity: 1,
    bubbleBorderWidth: 2,
    bubbleBorderStyle: 'solid',
    bubbleBorderColor: 'rgba(196, 16, 47, 0.7)',
    bubbleBorderOffset: null,
    bubbleBoxShadow: '0 0 14px rgba(196, 16, 47, 0.35), 0 0 26px rgba(212, 175, 55, 0.15)',
    bubbleGlow: 'drop-shadow(0 0 5px rgba(196, 16, 47, 0.4))',
    bubblePadding: null,
    bubblePaddingX: 16,
    bubblePaddingY: 9,
    bubblePaddingTop: null,
    bubblePaddingRight: null,
    bubblePaddingBottom: null,
    bubblePaddingLeft: null,
    bubbleTextureUrl: null,
    bubbleTextureSize: 'auto',
    bubbleTextureRepeat: 'repeat',
    bubbleTextureOpacity: 1,
    bubbleBunnyEars: false,
    bubbleBunnyEarsWidth: 32,
    bubbleBunnyEarsHeight: 30,
    bubbleBunnyEarsRoundness: 0,
    bubbleBunnyEarsOffsetX: 20,
    bubbleBunnyEarsOffsetY: 28,
    bubbleBunnyEarsRotate: 0,
    bubbleBunnyEarsZIndex: -1,
    bubbleMinWidth: 0,
    bubbleMaxWidth: 0,
    bubbleFixedWidth: 0,
    bubbleMinHeight: 0,
    bubbleMaxHeight: 0,
    bubbleFixedHeight: 0,
    avatarSize: 32,
    showAvatar: true,
    animationMs: 240,
    position: 'bottom-up',
    maxMessages: 40,
    poolWarmupSize: 20,
    idleAnimation: 'none',
    idleAnimationSpeed: 4,
    idleAnimationIntensity: 5,
    idleShimmerEnabled: true,
    idleShimmerSpeed: 2.2,
    idleShimmerIntensity: 6,
    emojiGlyphEnabled: true,
    emojiGlyphBg: 'rgba(196, 16, 47, 0.16)',
    emojiGlyphRadius: 4,
    emojiGlyphOpacity: 1,
    emojiGlyphGlow: 'drop-shadow(0 0 4px rgba(212, 175, 55, 0.35))',
  },
  layoutConfig: defaultLayout(),
  slotStyleConfig: defaultSlotStyle(),
  animationConfig: {
    enabled: true,
    style: 'blurZoom',
    targets: {
      avatar:   { durationMs: null, delayMs: 0, easing: 'ease-out', translateX: 0, translateY: 0, blur: 6 },
      author:   { durationMs: null, delayMs: 40, easing: 'ease-out', translateX: 0, translateY: 0, blur: 6 },
      message:  { durationMs: null, delayMs: 70, easing: 'ease-out', translateX: 0, translateY: 0, blur: 6 },
    },
  },
  decorationConfig: emptyDecorations(),
  roleStyleConfig: {
    roles: {
      moderator: {
      // The "saint" — halo gold, disciplined and bright.
      enabled: true,
      authorColor: '#F0DFA0',
      authorBorderColor: 'rgba(212, 175, 55, 0.75)',
      authorBg: null,
      messageBg: 'rgba(28, 22, 8, 0.92)',
      messageBorderColor: 'rgba(212, 175, 55, 0.5)',
      messageTextColor: '#F0DFA0',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: '👼',
      badgeAfter: null,
      authorFontWeight: 'extrabold',
      messageBorderWidth: null,
      textScale: null,
      memberTiers: [],
    },
      member: {
      enabled: true,
      authorColor: '#E86373',
      authorBorderColor: 'rgba(226, 58, 78, 0.55)',
      authorBg: null,
      messageBg: 'rgba(101, 29, 39, 0.94)',
      messageBorderColor: 'rgba(226, 58, 78, 0.4)',
      messageTextColor: '#EC818E',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: '🔥',
      badgeAfter: null,
      authorFontWeight: 'bold',
      messageBorderWidth: null,
      textScale: 1.12,
      memberTiers: [
        { id: 'tier-1mo', minMonths: 1, color: '#E86373', badge: '🔥' },
        { id: 'tier-3mo', minMonths: 3, color: '#F25973', badge: '😈' },
        { id: 'tier-6mo', minMonths: 6, color: '#F25974', badge: null },
        { id: 'tier-12mo', minMonths: 12, color: '#D4AF37', badge: '👑' },
      ],
    },
    },
  },
  fanServiceConfig: defaultThemeFanService({
    superchat: { authorColor: '#D4AF37', messageColor: '#EDE6DA' },
    membership: { authorColor: '#E86373', messageColor: '#EC818E', monthsColor: '#E86373' },
  }),
};
