// Theme preset: glassmorphism

const { defaultLayout, defaultSlotStyle, emptyDecorations, defaultThemeFanService } = require('../helpers');

module.exports = {
  id: 'glassmorphism',
  name: 'Glassmorphism',
  author: 'built-in',
  version: '1.1.0',
  description: 'Frosted-glass panel that leans all the way into transparency, with a soft frost-sweep shimmer and a brighter glass card for Super Chat.',
  category: 'colorful',
  tags: ["glass","blur","frosted","translucent"],
  createdAt: '2024-01-01',
  modifiedAt: '2026-07-30',
  customizeConfig: {
    fontFamily: 'Inter, system-ui, sans-serif',
    fontSize: 15,
    textAlign: 'left',
    textColor: '#F2F6FA',
    authorColor: '#8FD3FF',
    textGlow: 'drop-shadow(0 1px 3px rgba(0, 0, 0, 0.5))',
    textStrokeWidth: 0,
    textStrokeColor: null,
    bubbleBg: 'rgba(255, 255, 255, 0.92)',
    bubbleRadius: 16,
    bubbleOpacity: 1,
    bubbleBorderWidth: 1,
    bubbleBorderStyle: 'solid',
    bubbleBorderColor: 'rgba(255, 255, 255, 0.22)',
    bubbleBorderOffset: null,
    bubbleBoxShadow: '0 4px 24px rgba(0, 0, 0, 0.15), inset 0 1px 0 rgba(255, 255, 255, 0.16)',
    bubbleGlow: null,
    bubblePadding: null,
    bubblePaddingX: 14,
    bubblePaddingY: 8,
    bubblePaddingTop: null,
    bubblePaddingRight: null,
    bubblePaddingBottom: null,
    bubblePaddingLeft: null,
    bubbleTextureUrl: null,
    bubbleTextureSize: 'auto',
    bubbleTextureRepeat: 'repeat',
    bubbleTextureOpacity: 1,
    bubbleBunnyEars: false,
    bubbleBunnyEarsWidth: 32,
    bubbleBunnyEarsHeight: 30,
    bubbleBunnyEarsRoundness: 0,
    bubbleBunnyEarsOffsetX: 20,
    bubbleBunnyEarsOffsetY: 28,
    bubbleBunnyEarsRotate: 0,
    bubbleBunnyEarsZIndex: -1,
    bubbleMinWidth: 0,
    bubbleMaxWidth: 0,
    bubbleFixedWidth: 0,
    bubbleMinHeight: 0,
    bubbleMaxHeight: 0,
    bubbleFixedHeight: 0,
    avatarSize: 32,
    showAvatar: true,
    animationMs: 240,
    position: 'bottom-up',
    maxMessages: 40,
    idleAnimation: 'float',
    idleAnimationSpeed: 4.5,
    idleAnimationIntensity: 6.5,
    idleShimmerEnabled: true,
    idleShimmerSpeed: 3.5,
    idleShimmerIntensity: 7,
    emojiGlyphEnabled: true,
    emojiGlyphBg: 'rgba(255, 255, 255, 0.1)',
    emojiGlyphRadius: 6,
    emojiGlyphOpacity: 1,
    emojiGlyphGlow: null,
  },
  // Header/body split: a slightly brighter frosted band for the name, a
  // more transparent band underneath for the message — two glass panes
  // instead of one flat sheet.
  layoutConfig: defaultLayout({ screen: { headerSplit: true } }),
  slotStyleConfig: defaultSlotStyle({
    slots: {
      author: { bubbleBg: 'rgba(255, 255, 255, 0.22)' },
      message: { bubbleBg: 'rgba(255, 255, 255, 0.08)' },
    },
  }),
  animationConfig: {
    enabled: true,
    style: 'blurZoom',
    targets: {
      avatar:   { durationMs: null, delayMs: 0, easing: 'ease-out', translateX: 0, translateY: 0, blur: 10 },
      author:   { durationMs: null, delayMs: 40, easing: 'ease-out', translateX: 0, translateY: 0, blur: 10 },
      message:  { durationMs: null, delayMs: 80, easing: 'ease-out', translateX: 0, translateY: 0, blur: 10 },
    },
  },
  decorationConfig: emptyDecorations(),
  roleStyleConfig: {
    roles: {
      moderator: {
      enabled: true,
      authorColor: '#633632',
      authorBorderColor: 'rgba(255, 138, 128, 0.6)',
      authorBg: null,
      messageBg: 'rgba(255, 138, 128, 0.9)',
      messageBorderColor: 'rgba(255, 138, 128, 0.4)',
      messageTextColor: '#633632',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: null,
      memberTiers: [],
    },
      member: {
      enabled: true,
      authorColor: '#0071A2',
      authorBorderColor: 'rgba(128, 216, 255, 0.5)',
      authorBg: null,
      messageBg: 'rgba(202, 239, 255, 0.92)',
      messageBorderColor: 'rgba(128, 216, 255, 0.35)',
      messageTextColor: '#406B7E',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: 1.15,
      memberTiers: [
        { id: 'tier-1mo', minMonths: 1, color: '#0071A2', badge: null },
        { id: 'tier-3mo', minMonths: 3, color: '#0071A3', badge: null },
        { id: 'tier-6mo', minMonths: 6, color: '#7F36FF', badge: null },
        { id: 'tier-12mo', minMonths: 12, color: '#826700', badge: '👑' },
      ],
    },
    },
  },
  fanServiceConfig: defaultThemeFanService({
    superchat: { authorColor: '#8FD3FF', messageColor: '#F2F6FA' },
    membership: { authorColor: '#0071A2', messageColor: '#406B7E', monthsColor: '#0071A2' },
  }),
};
