/**
 * Theme preset: karaoke
 */

const { defaultLayout, defaultSlotStyle, emptyDecorations, defaultThemeFanService } = require('../helpers');

module.exports = {
  id: 'karaoke',
  name: 'Karaoke Night',
  author: 'built-in',
  version: '1.0.0',
  description: 'Bong bóng chat bay ngang màn hình như đèn laser phòng karaoke — chạy ở chế độ Danmaku (đạn bay), viền neon hồng/tím rực rỡ, chừa khoảng trống phía dưới cho phụ đề lời bài hát.',
  category: 'party',
  tags: ["karaoke","danmaku","party","neon","colorful"],
  createdAt: '2026-07-31',
  modifiedAt: '2026-07-31',
  customizeConfig: {
    fontFamily: '"Baloo 2", "Grandstander", system-ui, sans-serif',
    fontSize: 20,
    textAlign: 'left',
    textColor: '#FFF3FB',
    authorColor: '#FF3DAE',
    textGlow: 'drop-shadow(0 0 6px rgba(255, 61, 174, 0.5))',
    textStrokeWidth: 0,
    textStrokeColor: null,
    bubbleBg: 'rgba(58, 12, 82, 0.9)',
    bubbleRadius: 24,
    bubbleOpacity: 1,
    bubbleBorderWidth: 2,
    bubbleBorderStyle: 'solid',
    bubbleBorderColor: 'rgba(255, 61, 174, 0.65)',
    bubbleBorderOffset: null,
    bubbleBoxShadow: '0 0 18px rgba(255, 61, 174, 0.35), 0 0 32px rgba(123, 58, 237, 0.25)',
    bubbleGlow: 'drop-shadow(0 0 5px rgba(255, 61, 174, 0.45))',
    bubblePadding: null,
    bubblePaddingX: 16,
    bubblePaddingY: 8,
    bubblePaddingTop: null,
    bubblePaddingRight: null,
    bubblePaddingBottom: null,
    bubblePaddingLeft: null,
    bubbleTextureUrl: null,
    bubbleTextureSize: 'auto',
    bubbleTextureRepeat: 'repeat',
    bubbleTextureOpacity: 1,
    bubbleBunnyEars: false,
    bubbleBunnyEarsWidth: 32,
    bubbleBunnyEarsHeight: 30,
    bubbleBunnyEarsRoundness: 0,
    bubbleBunnyEarsOffsetX: 20,
    bubbleBunnyEarsOffsetY: 28,
    bubbleBunnyEarsRotate: 0,
    bubbleBunnyEarsZIndex: -1,
    bubbleMinWidth: 0,
    bubbleMaxWidth: 0,
    bubbleFixedWidth: 0,
    bubbleMinHeight: 0,
    bubbleMaxHeight: 0,
    bubbleFixedHeight: 0,
    avatarSize: 34,
    showAvatar: true,
    animationMs: 200,
    position: 'bottom-up',
    maxMessages: 40,
    poolWarmupSize: 20,
    // Danmaku — bullet comments fly right-to-left like karaoke-room laser
    // beams instead of stacking. Extra bottom clearance (20%) leaves room
    // for a lyrics/subtitle bar so bullets never fly over the song text.
    displayMode: 'danmaku',
    danmakuSpeed: 1,
    danmakuLanes: 10,
    danmakuAreaTopPct: 8,
    danmakuAreaBottomPct: 20,
    tickerSpeed: 1,
    tickerGap: 32,
    tickerPosition: 'bottom',
    idleAnimation: 'none',
    idleAnimationSpeed: 4,
    idleAnimationIntensity: 6.5,
    idleShimmerEnabled: false,
    idleShimmerSpeed: 2.4,
    idleShimmerIntensity: 7,
    emojiGlyphEnabled: true,
    emojiGlyphBg: 'rgba(255, 255, 255, 0.14)',
    emojiGlyphRadius: 10,
    emojiGlyphOpacity: 1,
    emojiGlyphGlow: 'drop-shadow(0 0 4px rgba(255, 61, 174, 0.4))',
  },
  layoutConfig: defaultLayout(),
  slotStyleConfig: defaultSlotStyle(),
  animationConfig: {
    enabled: true,
    style: 'bounce',
    targets: {
      avatar:   { durationMs: null, delayMs: 0, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0, translateY: 10, blur: 0 },
      author:   { durationMs: null, delayMs: 30, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: -8, translateY: 0, blur: 0 },
      message:  { durationMs: null, delayMs: 60, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0, translateY: 8, blur: 0 },
    },
  },
  decorationConfig: emptyDecorations(),
  roleStyleConfig: {
    roles: {
      moderator: {
      enabled: true,
      authorColor: '#00E5FF',
      authorBorderColor: 'rgba(0, 229, 255, 0.7)',
      authorBg: null,
      messageBg: 'rgba(8, 40, 56, 0.9)',
      messageBorderColor: 'rgba(0, 229, 255, 0.45)',
      messageTextColor: '#00E5FF',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: null,
      memberTiers: [],
    },
      member: {
      enabled: true,
      authorColor: '#FFD700',
      authorBorderColor: 'rgba(255, 215, 0, 0.55)',
      authorBg: null,
      messageBg: 'rgba(141, 97, 48, 0.9)',
      messageBorderColor: 'rgba(255, 215, 0, 0.45)',
      messageTextColor: '#FFEE94',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: '🎤',
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: 1.15,
      memberTiers: [
        { id: 'tier-1mo', minMonths: 1, color: '#FFD700', badge: '🎤' },
        { id: 'tier-3mo', minMonths: 3, color: '#FFC400', badge: '🎤🎤' },
        { id: 'tier-6mo', minMonths: 6, color: '#FFC068', badge: '🎤🎤🎤' },
        { id: 'tier-12mo', minMonths: 12, color: '#FFB5E0', badge: '👑' },
      ],
    },
    },
  },
  fanServiceConfig: defaultThemeFanService({
    superchat: { authorColor: '#FF3DAE', messageColor: '#FFF3FB' },
    membership: { authorColor: '#FFD700', messageColor: '#FFEE94', monthsColor: '#FFD700' },
  }),
};
