// Theme preset: maid

const { defaultLayout, defaultSlotStyle, emptyDecorations, defaultThemeFanService } = require('../helpers');

module.exports = {
  id: 'maid',
  name: 'Maid',
  author: 'built-in',
  version: '1.1.0',
  description: 'Maid café style — crisp glass-white bubble, black lace trim, cherry-red bow accent, and a full-bow spotlight for Super Chat.',
  category: 'cute',
  tags: ["maid","cute","white","black","red","lolita"],
  createdAt: '2026-07-13',
  modifiedAt: '2026-07-30',
  customizeConfig: {
    fontFamily: '"Poppins", "Quicksand", system-ui, sans-serif',
    fontSize: 15,
    textAlign: 'left',
    textColor: '#3A2E2E',
    authorColor: '#C81E3A',
    textGlow: null,
    textStrokeWidth: 0,
    textStrokeColor: null,
    bubbleBg: 'rgba(255, 250, 250, 0.92)',
    bubbleRadius: 16,
    bubbleOpacity: 1,
    bubbleBorderWidth: 2,
    bubbleBorderStyle: 'solid',
    bubbleBorderColor: 'rgba(30, 27, 27, 0.55)',
    bubbleBorderOffset: null,
    bubbleBoxShadow: '0 3px 14px rgba(0, 0, 0, 0.1)',
    bubbleGlow: null,
    bubblePadding: null,
    bubblePaddingX: null,
    bubblePaddingY: null,
    bubblePaddingTop: null,
    bubblePaddingRight: null,
    bubblePaddingBottom: null,
    bubblePaddingLeft: null,
    bubbleTextureUrl: null,
    bubbleTextureSize: 'auto',
    bubbleTextureRepeat: 'repeat',
    bubbleTextureOpacity: 1,
    bubbleBunnyEars: true,
    bubbleBunnyEarsWidth: 30,
    bubbleBunnyEarsHeight: 28,
    bubbleBunnyEarsRoundness: 6,
    bubbleBunnyEarsOffsetX: 18,
    bubbleBunnyEarsOffsetY: 26,
    bubbleBunnyEarsRotate: 0,
    bubbleBunnyEarsZIndex: -1,
    bubbleMinWidth: 0,
    bubbleMaxWidth: 0,
    bubbleFixedWidth: 0,
    bubbleMinHeight: 0,
    bubbleMaxHeight: 0,
    bubbleFixedHeight: 0,
    avatarSize: 32,
    showAvatar: true,
    animationMs: 260,
    position: 'bottom-up',
    maxMessages: 40,
    idleAnimation: 'float',
    idleAnimationSpeed: 5.5,
    idleAnimationIntensity: 5.5,
    idleShimmerEnabled: false,
    idleShimmerSpeed: 3,
    idleShimmerIntensity: 5,
    emojiGlyphEnabled: true,
    emojiGlyphBg: 'rgba(255, 255, 255, 0.1)',
    emojiGlyphRadius: 6,
    emojiGlyphOpacity: 1,
    emojiGlyphGlow: null,
  },
  layoutConfig: defaultLayout(),
  slotStyleConfig: defaultSlotStyle(),
  animationConfig: {
    enabled: true,
    style: 'bounce',
    targets: {
      avatar:   { durationMs: null, delayMs: 0, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0, translateY: 14, blur: 0 },
      author:   { durationMs: null, delayMs: 40, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: -10, translateY: 0, blur: 0 },
      message:  { durationMs: null, delayMs: 80, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0, translateY: 10, blur: 0 },
    },
  },
  decorationConfig: emptyDecorations(),
  roleStyleConfig: {
    roles: {
      moderator: {
      enabled: true,
      authorColor: '#1E1B1B',
      authorBorderColor: 'rgba(30, 27, 27, 0.7)',
      authorBg: null,
      messageBg: 'rgba(226, 221, 221, 0.9)',
      messageBorderColor: 'rgba(30, 27, 27, 0.4)',
      messageTextColor: '#1E1B1B',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: null,
      memberTiers: [],
    },
      member: {
      enabled: true,
      authorColor: '#8C1528',
      authorBorderColor: 'rgba(200, 30, 58, 0.5)',
      authorBg: null,
      messageBg: 'rgba(232, 158, 169, 0.92)',
      messageBorderColor: 'rgba(200, 30, 58, 0.35)',
      messageTextColor: '#851427',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: '🎀',
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: 1.15,
      memberTiers: [
        { id: 'tier-1mo', minMonths: 1, color: '#8C1528', badge: '🎀' },
        { id: 'tier-3mo', minMonths: 3, color: '#8B0000', badge: '🎀🎀' },
        { id: 'tier-6mo', minMonths: 6, color: '#1E1B1B', badge: '🍰' },
        { id: 'tier-12mo', minMonths: 12, color: '#59440A', badge: '👑' },
      ],
    },
    },
  },
  fanServiceConfig: defaultThemeFanService({
    superchat: { authorColor: '#C81E3A', messageColor: '#3A2E2E' },
    membership: { authorColor: '#8C1528', messageColor: '#851427', monthsColor: '#8C1528' },
  }),
};
