/**
 * Theme preset: minimal-dark
 */

const { defaultLayout, defaultSlotStyle, emptyDecorations } = require('../helpers');

module.exports = {
  id: 'minimal-dark',
  name: 'Minimal Dark',
  author: 'built-in',
  version: '1.1.0',
  description: 'Clean dark glass panel with light text — minimal, modern, unobtrusive, with a crisp Super Chat/Membership highlight.',
  category: 'minimal',
  tags: ["minimal","dark","clean"],
  createdAt: '2024-01-01',
  modifiedAt: '2026-07-30',
  customizeConfig: {
    fontFamily: 'Inter, system-ui, sans-serif',
    fontSize: 15,
    textAlign: 'left',
    textColor: '#EAECEF',
    authorColor: '#818CF8',
    textGlow: 'drop-shadow(0 1px 2px rgba(0, 0, 0, 0.8))',
    textStrokeWidth: 0,
    textStrokeColor: null,
    bubbleBg: 'rgba(15, 17, 23, 0.92)',
    bubbleRadius: 8,
    bubbleOpacity: 1,
    bubbleBorderWidth: 1,
    bubbleBorderStyle: 'solid',
    bubbleBorderColor: 'rgba(255, 255, 255, 0.08)',
    bubbleBorderOffset: null,
    bubbleBoxShadow: null,
    bubbleGlow: null,
    bubblePadding: null,
    bubblePaddingX: 12,
    bubblePaddingY: 6,
    bubblePaddingTop: null,
    bubblePaddingRight: null,
    bubblePaddingBottom: null,
    bubblePaddingLeft: null,
    bubbleTextureUrl: null,
    bubbleTextureSize: 'auto',
    bubbleTextureRepeat: 'repeat',
    bubbleTextureOpacity: 1,
    bubbleBunnyEars: false,
    bubbleBunnyEarsWidth: 32,
    bubbleBunnyEarsHeight: 30,
    bubbleBunnyEarsRoundness: 0,
    bubbleBunnyEarsOffsetX: 20,
    bubbleBunnyEarsOffsetY: 28,
    bubbleBunnyEarsRotate: 0,
    bubbleBunnyEarsZIndex: -1,
    bubbleMinWidth: 0,
    bubbleMaxWidth: 0,
    bubbleFixedWidth: 0,
    bubbleMinHeight: 0,
    bubbleMaxHeight: 0,
    bubbleFixedHeight: 0,
    avatarSize: 24,
    showAvatar: false,
    showBadges: false,
    animationMs: 160,
    position: 'bottom-up',
    maxMessages: 30,
    idleAnimation: 'float',
    idleAnimationSpeed: 6,
    idleAnimationIntensity: 5,
    idleShimmerEnabled: false,
    idleShimmerSpeed: 3,
    idleShimmerIntensity: 5,
    emojiGlyphEnabled: true,
    emojiGlyphBg: 'rgba(255, 255, 255, 0.1)',
    emojiGlyphRadius: 6,
    emojiGlyphOpacity: 1,
    emojiGlyphGlow: null,
  },
  layoutConfig: defaultLayout(),
  slotStyleConfig: defaultSlotStyle(),
  animationConfig: {
    enabled: true,
    style: 'slide',
    targets: {
      avatar:   { durationMs: null, delayMs: 0, easing: 'ease-out', translateX: 0, translateY: 8, blur: 0 },
      author:   { durationMs: null, delayMs: 40, easing: 'ease-out', translateX: -6, translateY: 0, blur: 0 },
      badges:   { durationMs: null, delayMs: 60, easing: 'ease-out', translateX: -4, translateY: 0, blur: 0 },
      message:  { durationMs: null, delayMs: 80, easing: 'ease-out', translateX: 0, translateY: 6, blur: 0 },
    },
  },
  decorationConfig: emptyDecorations(),
  roleStyleConfig: {
    roles: {
      moderator: {
      enabled: true,
      authorColor: '#fca5a5',
      authorBorderColor: 'rgba(248, 113, 113, 0.7)',
      authorBg: null,
      messageBg: 'rgba(86, 50, 54, 0.9)',
      messageBorderColor: 'rgba(248, 113, 113, 0.45)',
      messageTextColor: '#fca5a5',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      showAmount: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: null,
      memberTiers: [],
    },
      member: {
      // Renewal ("Gia hạn") stand-out layout — glowing bubble, not the
      // two-tier YouTube card, so it reads as "special" without breaking
      // the theme's own bubble silhouette.
      milestoneLayout: 'highlight',
      enabled: true,
      authorColor: '#93c5fd',
      authorBorderColor: 'rgba(96, 165, 250, 0.55)',
      authorBg: null,
      messageBg: 'rgba(70, 93, 120, 0.92)',
      messageBorderColor: 'rgba(96, 165, 250, 0.45)',
      messageTextColor: '#BBDBFE',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      showAmount: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: 1.15,
      memberTiers: [
        { id: 'tier-1mo', minMonths: 1, color: '#93c5fd', badge: null },
        { id: 'tier-3mo', minMonths: 3, color: '#8BBDFB', badge: null },
        { id: 'tier-6mo', minMonths: 6, color: '#AEB5FA', badge: null },
        { id: 'tier-12mo', minMonths: 12, color: '#facc15', badge: '👑' },
      ],
    },
      superchat: {
      enabled: true,
      authorColor: '#fde047',
      authorBorderColor: 'rgba(255, 202, 40, 0.6)',
      authorBg: null,
      messageBg: 'rgba(88, 75, 34, 0.92)',
      messageBorderColor: 'rgba(255, 202, 40, 0.5)',
      messageTextColor: '#fde047',
      rowBg: 'rgba(88, 75, 34, 0.92)',
      rowBorderColor: 'rgba(255, 202, 40, 0.5)',
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      showAmount: true,
      fontSize: null,
      authorFontWeight: null,
      messageBorderWidth: 2,
      textScale: 1.3,
      memberTiers: [],
      useTierColor: true,
      superchatLayout: 'youtube',
      amountFontSize: null,
      amountFontWeight: 'extrabold',
      amountPosition: 'block',
    },
    },
  },
};
