/**
 * Theme preset: minimal-white
 */

const { defaultLayout, defaultSlotStyle, emptyDecorations, defaultThemeFanService } = require('../helpers');

module.exports = {
  id: 'minimal-white',
  name: 'Minimal White',
  author: 'built-in',
  version: '1.1.0',
  description: 'Clean white glass panel with dark text — minimal, airy, and highly readable, Super Chat still lands clearly.',
  category: 'minimal',
  tags: ["minimal","light","clean"],
  createdAt: '2024-01-01',
  modifiedAt: '2026-07-30',
  customizeConfig: {
    fontFamily: 'Inter, system-ui, sans-serif',
    fontSize: 15,
    textAlign: 'left',
    textColor: '#1E293B',
    authorColor: '#2563EB',
    textGlow: null,
    textStrokeWidth: 0,
    textStrokeColor: null,
    bubbleBg: 'rgba(255, 255, 255, 0.92)',
    bubbleRadius: 8,
    bubbleOpacity: 1,
    bubbleBorderWidth: 1,
    bubbleBorderStyle: 'solid',
    bubbleBorderColor: 'rgba(30, 41, 59, 0.12)',
    bubbleBorderOffset: null,
    bubbleBoxShadow: null,
    bubbleGlow: null,
    bubblePadding: null,
    bubblePaddingX: 12,
    bubblePaddingY: 6,
    bubblePaddingTop: null,
    bubblePaddingRight: null,
    bubblePaddingBottom: null,
    bubblePaddingLeft: null,
    bubbleTextureUrl: null,
    bubbleTextureSize: 'auto',
    bubbleTextureRepeat: 'repeat',
    bubbleTextureOpacity: 1,
    bubbleBunnyEars: false,
    bubbleBunnyEarsWidth: 32,
    bubbleBunnyEarsHeight: 30,
    bubbleBunnyEarsRoundness: 0,
    bubbleBunnyEarsOffsetX: 20,
    bubbleBunnyEarsOffsetY: 28,
    bubbleBunnyEarsRotate: 0,
    bubbleBunnyEarsZIndex: -1,
    bubbleMinWidth: 0,
    bubbleMaxWidth: 0,
    bubbleFixedWidth: 0,
    bubbleMinHeight: 0,
    bubbleMaxHeight: 0,
    bubbleFixedHeight: 0,
    avatarSize: 24,
    showAvatar: false,
    animationMs: 160,
    position: 'bottom-up',
    maxMessages: 30,
    idleAnimation: 'float',
    idleAnimationSpeed: 6,
    idleAnimationIntensity: 5,
    idleShimmerEnabled: false,
    idleShimmerSpeed: 3,
    idleShimmerIntensity: 5,
    emojiGlyphEnabled: true,
    emojiGlyphBg: 'rgba(255, 255, 255, 0.1)',
    emojiGlyphRadius: 6,
    emojiGlyphOpacity: 1,
    emojiGlyphGlow: null,
  },
  layoutConfig: defaultLayout(),
  slotStyleConfig: defaultSlotStyle(),
  animationConfig: {
    enabled: true,
    style: 'slide',
    targets: {
      avatar:   { durationMs: null, delayMs: 0, easing: 'ease-out', translateX: 0, translateY: 8, blur: 0 },
      author:   { durationMs: null, delayMs: 40, easing: 'ease-out', translateX: -6, translateY: 0, blur: 0 },
      message:  { durationMs: null, delayMs: 80, easing: 'ease-out', translateX: 0, translateY: 6, blur: 0 },
    },
  },
  decorationConfig: emptyDecorations(),
  roleStyleConfig: {
    roles: {
      moderator: {
      enabled: true,
      authorColor: '#510E0E',
      authorBorderColor: 'rgba(220, 38, 38, 0.5)',
      authorBg: null,
      messageBg: 'rgba(220, 38, 38, 0.9)',
      messageBorderColor: 'rgba(220, 38, 38, 0.3)',
      messageTextColor: '#510E0E',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: null,
      memberTiers: [],
    },
      member: {
      enabled: true,
      authorColor: '#1144B6',
      authorBorderColor: 'rgba(37, 99, 235, 0.4)',
      authorBg: null,
      messageBg: 'rgba(163, 189, 247, 0.92)',
      messageBorderColor: 'rgba(37, 99, 235, 0.28)',
      messageTextColor: '#1042AE',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: 1.15,
      memberTiers: [
        { id: 'tier-1mo', minMonths: 1, color: '#1144B6', badge: null },
        { id: 'tier-3mo', minMonths: 3, color: '#1943B9', badge: null },
        { id: 'tier-6mo', minMonths: 6, color: '#5C14D7', badge: null },
        { id: 'tier-12mo', minMonths: 12, color: '#6A4802', badge: '👑' },
      ],
    },
    },
  },
  fanServiceConfig: defaultThemeFanService({
    superchat: { authorColor: '#2563EB', messageColor: '#1E293B' },
    membership: { authorColor: '#1144B6', messageColor: '#1042AE', monthsColor: '#1144B6' },
  }),
};
