/**
 * Theme preset: neon
 */

const { defaultLayout, defaultSlotStyle, emptyDecorations } = require('../helpers');

module.exports = {
  id: 'neon',
  name: 'Neon',
  author: 'built-in',
  version: '1.1.0',
  description: 'Dark terminal bubble with teal-green neon border and double drop-shadow glow — glass-transparent at rest, Super Chat overdrives the glow.',
  category: 'gaming',
  tags: ["neon","glow","monospace","teal","gaming"],
  createdAt: '2024-01-01',
  modifiedAt: '2026-07-30',
  customizeConfig: {
    fontFamily: 'ui-monospace, "JetBrains Mono", monospace',
    fontSize: 14,
    textAlign: 'left',
    textColor: '#EAECEF',
    authorColor: '#35E6B0',
    textGlow: 'drop-shadow(0 0 3px rgba(53, 230, 176, 0.3))',
    textStrokeWidth: 0,
    textStrokeColor: null,
    bubbleBg: 'rgba(14, 16, 19, 0.92)',
    bubbleRadius: 10,
    bubbleOpacity: 1,
    bubbleBorderWidth: 2,
    bubbleBorderStyle: 'solid',
    bubbleBorderColor: 'rgba(53, 230, 176, 0.55)',
    bubbleBorderOffset: null,
    bubbleBoxShadow: '0 0 14px rgba(53, 230, 176, 0.25)',
    bubbleGlow: 'drop-shadow(0 0 4px rgba(53, 230, 176, 0.4))',
    bubblePadding: null,
    bubblePaddingX: 12,
    bubblePaddingY: 6,
    bubblePaddingTop: null,
    bubblePaddingRight: null,
    bubblePaddingBottom: null,
    bubblePaddingLeft: null,
    bubbleTextureUrl: null,
    bubbleTextureSize: 'auto',
    bubbleTextureRepeat: 'repeat',
    bubbleTextureOpacity: 1,
    bubbleBunnyEars: false,
    bubbleBunnyEarsWidth: 32,
    bubbleBunnyEarsHeight: 30,
    bubbleBunnyEarsRoundness: 0,
    bubbleBunnyEarsOffsetX: 20,
    bubbleBunnyEarsOffsetY: 28,
    bubbleBunnyEarsRotate: 0,
    bubbleBunnyEarsZIndex: -1,
    bubbleMinWidth: 0,
    bubbleMaxWidth: 0,
    bubbleFixedWidth: 0,
    bubbleMinHeight: 0,
    bubbleMaxHeight: 0,
    bubbleFixedHeight: 0,
    avatarSize: 28,
    showAvatar: true,
    showBadges: false,
    animationMs: 180,
    position: 'bottom-up',
    maxMessages: 40,
    idleAnimation: 'float',
    idleAnimationSpeed: 3.5,
    idleAnimationIntensity: 6.5,
    idleShimmerEnabled: true,
    idleShimmerSpeed: 2.6,
    idleShimmerIntensity: 6,
    emojiGlyphEnabled: true,
    emojiGlyphBg: 'rgba(255, 255, 255, 0.1)',
    emojiGlyphRadius: 6,
    emojiGlyphOpacity: 1,
    emojiGlyphGlow: null,
  },
  layoutConfig: defaultLayout(),
  slotStyleConfig: defaultSlotStyle(),
  animationConfig: {
    enabled: true,
    style: 'slideStrong',
    targets: {
      avatar:   { durationMs: null, delayMs: 0, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', translateX: 0, translateY: 40, blur: 0 },
      author:   { durationMs: null, delayMs: 40, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', translateX: -30, translateY: 0, blur: 0 },
      badges:   { durationMs: null, delayMs: 60, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', translateX: -20, translateY: 0, blur: 0 },
      message:  { durationMs: null, delayMs: 80, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', translateX: 0, translateY: 30, blur: 0 },
    },
  },
  decorationConfig: emptyDecorations(),
  roleStyleConfig: {
    roles: {
      moderator: {
      enabled: true,
      authorColor: '#FF4081',
      authorBorderColor: 'rgba(255, 64, 129, 0.7)',
      authorBg: null,
      messageBg: 'rgba(63, 26, 42, 0.9)',
      messageBorderColor: 'rgba(255, 64, 129, 0.45)',
      messageTextColor: '#FF4081',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      showAmount: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: null,
      memberTiers: [],
    },
      member: {
      // Renewal ("Gia hạn") stand-out layout — glowing bubble, not the
      // two-tier YouTube card, so it reads as "special" without breaking
      // the theme's own bubble silhouette.
      milestoneLayout: 'highlight',
      enabled: true,
      authorColor: '#69F0AE',
      authorBorderColor: 'rgba(105, 240, 174, 0.55)',
      authorBg: null,
      messageBg: 'rgba(52, 110, 84, 0.92)',
      messageBorderColor: 'rgba(105, 240, 174, 0.4)',
      messageTextColor: '#97F5C7',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      showAmount: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: 1.15,
      memberTiers: [
        { id: 'tier-1mo', minMonths: 1, color: '#69F0AE', badge: null },
        { id: 'tier-3mo', minMonths: 3, color: '#35E6B0', badge: null },
        { id: 'tier-6mo', minMonths: 6, color: '#00E5FF', badge: null },
        { id: 'tier-12mo', minMonths: 12, color: '#FFE57F', badge: null },
      ],
    },
      superchat: {
      enabled: true,
      authorColor: '#FFE57F',
      authorBorderColor: 'rgba(255, 229, 127, 0.7)',
      authorBg: null,
      messageBg: 'rgba(74, 69, 46, 0.92)',
      messageBorderColor: 'rgba(255, 229, 127, 0.55)',
      messageTextColor: '#FFE57F',
      rowBg: 'rgba(55, 53, 38, 0.92)',
      rowBorderColor: 'rgba(255, 229, 127, 0.55)',
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      showAmount: true,
      fontSize: null,
      authorFontWeight: null,
      messageBorderWidth: 2,
      textScale: 1.3,
      memberTiers: [],
      useTierColor: false,
      superchatLayout: 'youtube',
      amountFontSize: null,
      amountFontWeight: 'extrabold',
      amountPosition: 'block',
    },
    },
  },
};
