// Theme preset: night-sky

const { defaultLayout, defaultSlotStyle, emptyDecorations, defaultThemeFanService } = require('../helpers');

module.exports = {
  id: 'night-sky',
  name: 'Night Sky',
  author: 'built-in',
  version: '1.1.0',
  description: 'Deep navy glass with star-white text and a soft aurora sweep — Super Chat flares up like a shooting star.',
  category: 'dark',
  tags: ["dark","night","navy","aurora","purple"],
  createdAt: '2024-01-01',
  modifiedAt: '2026-07-30',
  customizeConfig: {
    fontFamily: '"Raleway", "Segoe UI", system-ui, sans-serif',
    fontSize: 15,
    textAlign: 'left',
    textColor: '#E8EAF6',
    authorColor: '#B39DDB',
    textGlow: 'drop-shadow(0 1px 3px rgba(0, 0, 0, 0.7))',
    textStrokeWidth: 0,
    textStrokeColor: null,
    bubbleBg: 'rgba(13, 14, 33, 0.92)',
    bubbleRadius: 12,
    bubbleOpacity: 1,
    bubbleBorderWidth: 1,
    bubbleBorderStyle: 'solid',
    bubbleBorderColor: 'rgba(179, 157, 219, 0.28)',
    bubbleBorderOffset: null,
    bubbleBoxShadow: '0 2px 20px rgba(13, 14, 33, 0.35)',
    bubbleGlow: 'drop-shadow(0 0 5px rgba(179, 157, 219, 0.16))',
    bubblePadding: null,
    bubblePaddingX: 14,
    bubblePaddingY: 8,
    bubblePaddingTop: null,
    bubblePaddingRight: null,
    bubblePaddingBottom: null,
    bubblePaddingLeft: null,
    bubbleTextureUrl: null,
    bubbleTextureSize: 'auto',
    bubbleTextureRepeat: 'repeat',
    bubbleTextureOpacity: 1,
    bubbleBunnyEars: false,
    bubbleBunnyEarsWidth: 32,
    bubbleBunnyEarsHeight: 30,
    bubbleBunnyEarsRoundness: 0,
    bubbleBunnyEarsOffsetX: 20,
    bubbleBunnyEarsOffsetY: 28,
    bubbleBunnyEarsRotate: 0,
    bubbleBunnyEarsZIndex: -1,
    bubbleMinWidth: 0,
    bubbleMaxWidth: 0,
    bubbleFixedWidth: 0,
    bubbleMinHeight: 0,
    bubbleMaxHeight: 0,
    bubbleFixedHeight: 0,
    avatarSize: 32,
    showAvatar: true,
    animationMs: 280,
    position: 'bottom-up',
    maxMessages: 40,
    idleAnimation: 'float',
    idleAnimationSpeed: 5,
    idleAnimationIntensity: 6,
    idleShimmerEnabled: true,
    idleShimmerSpeed: 4,
    idleShimmerIntensity: 5,
    emojiGlyphEnabled: true,
    emojiGlyphBg: 'rgba(255, 255, 255, 0.1)',
    emojiGlyphRadius: 6,
    emojiGlyphOpacity: 1,
    emojiGlyphGlow: null,
  },
  layoutConfig: defaultLayout(),
  slotStyleConfig: defaultSlotStyle(),
  animationConfig: {
    enabled: true,
    style: 'blurZoom',
    targets: {
      avatar:   { durationMs: null, delayMs: 0, easing: 'ease-out', translateX: 0, translateY: 0, blur: 8 },
      author:   { durationMs: null, delayMs: 40, easing: 'ease-out', translateX: 0, translateY: 0, blur: 8 },
      message:  { durationMs: null, delayMs: 80, easing: 'ease-out', translateX: 0, translateY: 0, blur: 8 },
    },
  },
  decorationConfig: emptyDecorations(),
  roleStyleConfig: {
    roles: {
      moderator: {
      enabled: true,
      authorColor: '#EF9A9A',
      authorBorderColor: 'rgba(239, 154, 154, 0.65)',
      authorBg: null,
      messageBg: 'rgba(59, 43, 58, 0.9)',
      messageBorderColor: 'rgba(239, 154, 154, 0.4)',
      messageTextColor: '#EF9A9A',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: null,
      memberTiers: [],
    },
      member: {
      enabled: true,
      authorColor: '#90CAF9',
      authorBorderColor: 'rgba(144, 202, 249, 0.55)',
      authorBg: null,
      messageBg: 'rgba(68, 93, 124, 0.92)',
      messageBorderColor: 'rgba(144, 202, 249, 0.38)',
      messageTextColor: '#B2DAFB',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: 1.15,
      memberTiers: [
        { id: 'tier-1mo', minMonths: 1, color: '#90CAF9', badge: null },
        { id: 'tier-3mo', minMonths: 3, color: '#C4B2E2', badge: null },
        { id: 'tier-6mo', minMonths: 6, color: '#D9AAE0', badge: '☄' },
        { id: 'tier-12mo', minMonths: 12, color: '#FFF176', badge: '👑' },
      ],
    },
    },
  },
  fanServiceConfig: defaultThemeFanService({
    superchat: { authorColor: '#B39DDB', messageColor: '#E8EAF6' },
    membership: { authorColor: '#90CAF9', messageColor: '#B2DAFB', monthsColor: '#90CAF9' },
  }),
};
