/**
 * Theme preset: pastel-pink
 */

const { defaultLayout, defaultSlotStyle, emptyDecorations } = require('../helpers');

module.exports = {
  id: 'pastel-pink',
  name: 'Pastel Pink',
  author: 'built-in',
  version: '1.1.0',
  description: 'Soft pink glass bubbles with warm purple author names — dreamy and light, with a gently bigger Super Chat spotlight.',
  category: 'cute',
  tags: ["cute","pink","pastel","soft"],
  createdAt: '2024-01-01',
  modifiedAt: '2026-07-30',
  customizeConfig: {
    fontFamily: '"Nunito", "Varela Round", system-ui, sans-serif',
    fontSize: 15,
    textAlign: 'left',
    textColor: '#4A2E4E',
    authorColor: '#C45594',
    textGlow: null,
    textStrokeWidth: 0,
    textStrokeColor: null,
    bubbleBg: 'rgba(255, 214, 234, 0.92)',
    bubbleRadius: 18,
    bubbleOpacity: 1,
    bubbleBorderWidth: 1,
    bubbleBorderStyle: 'solid',
    bubbleBorderColor: 'rgba(196, 85, 148, 0.3)',
    bubbleBorderOffset: null,
    bubbleBoxShadow: '0 2px 12px rgba(196, 85, 148, 0.10)',
    bubbleGlow: null,
    bubblePadding: null,
    bubblePaddingX: 14,
    bubblePaddingY: 8,
    bubblePaddingTop: null,
    bubblePaddingRight: null,
    bubblePaddingBottom: null,
    bubblePaddingLeft: null,
    bubbleTextureUrl: null,
    bubbleTextureSize: 'auto',
    bubbleTextureRepeat: 'repeat',
    bubbleTextureOpacity: 1,
    bubbleBunnyEars: false,
    bubbleBunnyEarsWidth: 32,
    bubbleBunnyEarsHeight: 30,
    bubbleBunnyEarsRoundness: 0,
    bubbleBunnyEarsOffsetX: 20,
    bubbleBunnyEarsOffsetY: 28,
    bubbleBunnyEarsRotate: 0,
    bubbleBunnyEarsZIndex: -1,
    bubbleMinWidth: 0,
    bubbleMaxWidth: 0,
    bubbleFixedWidth: 0,
    bubbleMinHeight: 0,
    bubbleMaxHeight: 0,
    bubbleFixedHeight: 0,
    avatarSize: 30,
    showAvatar: true,
    showBadges: false,
    animationMs: 280,
    position: 'bottom-up',
    maxMessages: 35,
    idleAnimation: 'float',
    idleAnimationSpeed: 4,
    idleAnimationIntensity: 6.5,
    idleShimmerEnabled: true,
    idleShimmerSpeed: 4.5,
    idleShimmerIntensity: 4,
    emojiGlyphEnabled: true,
    emojiGlyphBg: 'rgba(255, 255, 255, 0.1)',
    emojiGlyphRadius: 6,
    emojiGlyphOpacity: 1,
    emojiGlyphGlow: null,
  },
  layoutConfig: defaultLayout(),
  slotStyleConfig: defaultSlotStyle(),
  animationConfig: {
    enabled: true,
    style: 'bounce',
    targets: {
      avatar:   { durationMs: null, delayMs: 0, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0, translateY: 16, blur: 0 },
      author:   { durationMs: null, delayMs: 40, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: -12, translateY: 0, blur: 0 },
      badges:   { durationMs: null, delayMs: 60, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: -8, translateY: 0, blur: 0 },
      message:  { durationMs: null, delayMs: 80, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0, translateY: 12, blur: 0 },
    },
  },
  decorationConfig: emptyDecorations(),
  roleStyleConfig: {
    roles: {
      moderator: {
      enabled: true,
      authorColor: '#E91E8C',
      authorBorderColor: 'rgba(233, 30, 140, 0.6)',
      authorBg: null,
      messageBg: 'rgba(251, 179, 216, 0.9)',
      messageBorderColor: 'rgba(233, 30, 140, 0.35)',
      messageTextColor: '#A51563',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      showAmount: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: null,
      memberTiers: [],
    },
      member: {
      // Renewal ("Gia hạn") stand-out layout — glowing bubble, not the
      // two-tier YouTube card, so it reads as "special" without breaking
      // the theme's own bubble silhouette.
      milestoneLayout: 'highlight',
      enabled: true,
      authorColor: '#3519DD',
      authorBorderColor: 'rgba(123, 104, 238, 0.5)',
      authorBg: null,
      messageBg: 'rgba(200, 168, 236, 0.92)',
      messageBorderColor: 'rgba(123, 104, 238, 0.35)',
      messageTextColor: '#43349B',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      showAmount: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: 1.15,
      memberTiers: [
        { id: 'tier-1mo', minMonths: 1, color: '#3519DD', badge: '🌷' },
        { id: 'tier-3mo', minMonths: 3, color: '#7B2B59', badge: '🌷🌷' },
        { id: 'tier-6mo', minMonths: 6, color: '#6E3D00', badge: '🎀' },
        { id: 'tier-12mo', minMonths: 12, color: '#564800', badge: '👑' },
      ],
    },
      superchat: {
      enabled: true,
      authorColor: '#FF8C00',
      authorBorderColor: 'rgba(255, 140, 0, 0.55)',
      authorBg: null,
      messageBg: 'rgba(255, 196, 176, 0.92)',
      messageBorderColor: 'rgba(255, 140, 0, 0.45)',
      messageTextColor: '#8C4D00',
      rowBg: 'rgba(255, 196, 176, 0.92)',
      rowBorderColor: 'rgba(255, 140, 0, 0.45)',
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      showAmount: true,
      fontSize: null,
      authorFontWeight: null,
      messageBorderWidth: 2,
      textScale: 1.3,
      memberTiers: [],
      useTierColor: false,
      superchatLayout: 'youtube',
      amountFontSize: null,
      amountFontWeight: 'extrabold',
      amountPosition: 'block',
    },
    },
  },
};
