// Theme preset: retro

const { defaultLayout, defaultSlotStyle, emptyDecorations, defaultThemeFanService } = require('../helpers');

module.exports = {
  id: 'retro',
  name: 'Retro',
  author: 'built-in',
  version: '1.1.0',
  description: 'Warm parchment bubbles with a monospace font and hard ink border — vintage terminal vibes, dialled down to a light wash so the feed stays airy.',
  category: 'dark',
  tags: ["retro","monospace","vintage","light"],
  createdAt: '2024-01-01',
  modifiedAt: '2026-07-30',
  customizeConfig: {
    fontFamily: 'ui-monospace, "JetBrains Mono", monospace',
    fontSize: 14,
    textAlign: 'left',
    textColor: '#2B1B0E',
    authorColor: '#B8410C',
    textGlow: null,
    textStrokeWidth: 0,
    textStrokeColor: null,
    bubbleBg: 'rgba(245, 224, 178, 0.92)',
    bubbleRadius: 4,
    bubbleOpacity: 1,
    bubbleBorderWidth: 2,
    bubbleBorderStyle: 'solid',
    bubbleBorderColor: 'rgba(43, 27, 14, 0.7)',
    bubbleBorderOffset: null,
    bubbleBoxShadow: null,
    bubbleGlow: null,
    bubblePadding: null,
    bubblePaddingX: null,
    bubblePaddingY: null,
    bubblePaddingTop: null,
    bubblePaddingRight: null,
    bubblePaddingBottom: null,
    bubblePaddingLeft: null,
    bubbleTextureUrl: null,
    bubbleTextureSize: 'auto',
    bubbleTextureRepeat: 'repeat',
    bubbleTextureOpacity: 1,
    bubbleBunnyEars: false,
    bubbleBunnyEarsWidth: 32,
    bubbleBunnyEarsHeight: 30,
    bubbleBunnyEarsRoundness: 0,
    bubbleBunnyEarsOffsetX: 20,
    bubbleBunnyEarsOffsetY: 28,
    bubbleBunnyEarsRotate: 0,
    bubbleBunnyEarsZIndex: -1,
    bubbleMinWidth: 0,
    bubbleMaxWidth: 0,
    bubbleFixedWidth: 0,
    bubbleMinHeight: 0,
    bubbleMaxHeight: 0,
    bubbleFixedHeight: 0,
    avatarSize: 32,
    showAvatar: true,
    animationMs: 200,
    position: 'bottom-up',
    maxMessages: 40,
    idleAnimation: 'float',
    idleAnimationSpeed: 6,
    idleAnimationIntensity: 5,
    idleShimmerEnabled: false,
    idleShimmerSpeed: 3,
    idleShimmerIntensity: 5,
    emojiGlyphEnabled: true,
    emojiGlyphBg: 'rgba(255, 255, 255, 0.1)',
    emojiGlyphRadius: 6,
    emojiGlyphOpacity: 1,
    emojiGlyphGlow: null,
  },
  // Telegram-slip header/body split — a darker ink band for the "FROM"
  // line, a lighter parchment band underneath for the wired-in message.
  layoutConfig: defaultLayout({ screen: { headerSplit: true } }),
  slotStyleConfig: defaultSlotStyle({
    slots: {
      author: { bubbleBg: 'rgba(184, 65, 12, 0.16)' },
      message: { bubbleBg: 'rgba(245, 224, 178, 0.92)' },
    },
  }),
  animationConfig: {
    enabled: true,
    style: 'slide',
    targets: {
      avatar:   { durationMs: null, delayMs: 0, easing: 'ease-out', translateX: 0, translateY: 8, blur: 0 },
      author:   { durationMs: null, delayMs: 40, easing: 'ease-out', translateX: -6, translateY: 0, blur: 0 },
      message:  { durationMs: null, delayMs: 80, easing: 'ease-out', translateX: 0, translateY: 6, blur: 0 },
    },
  },
  decorationConfig: emptyDecorations(),
  roleStyleConfig: {
    roles: {
      moderator: {
      enabled: true,
      authorColor: '#8B0000',
      authorBorderColor: 'rgba(139, 0, 0, 0.7)',
      authorBg: null,
      messageBg: 'rgba(255, 220, 220, 0.9)',
      messageBorderColor: 'rgba(139, 0, 0, 0.45)',
      messageTextColor: '#8B0000',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: null,
      memberTiers: [],
    },
      member: {
      enabled: true,
      authorColor: '#143A6A',
      authorBorderColor: 'rgba(26, 77, 140, 0.55)',
      authorBg: null,
      messageBg: 'rgba(153, 162, 162, 0.92)',
      messageBorderColor: 'rgba(26, 77, 140, 0.4)',
      messageTextColor: '#123561',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: 1.15,
      memberTiers: [
        { id: 'tier-1mo', minMonths: 1, color: '#143A6A', badge: null },
        { id: 'tier-3mo', minMonths: 3, color: '#672507', badge: null },
        { id: 'tier-6mo', minMonths: 6, color: '#234120', badge: null },
        { id: 'tier-12mo', minMonths: 12, color: '#543300', badge: null },
      ],
    },
    },
  },
  fanServiceConfig: defaultThemeFanService({
    superchat: { authorColor: '#B8410C', messageColor: '#2B1B0E' },
    membership: { authorColor: '#143A6A', messageColor: '#123561', monthsColor: '#143A6A' },
  }),
};
