/**
 * Theme preset: ticker-news
 */

const { defaultLayout, defaultSlotStyle, emptyDecorations } = require('../helpers');

module.exports = {
  id: 'ticker-news',
  name: 'Ticker News',
  author: 'built-in',
  version: '2.0.0',
  description: 'Chạy tin nhắn như bảng tin nóng dưới đáy màn hình — chế độ Chat Ticker, nền trắng chữ đỏ/đen sắc nét, đúng tông trắng-đỏ của các bản tin thời sự "breaking news".',
  category: 'news',
  tags: ["ticker","news","breaking","white","red","bold"],
  createdAt: '2026-07-31',
  modifiedAt: '2026-07-31',
  customizeConfig: {
    fontFamily: '"Exo 2", "Space Grotesk", system-ui, sans-serif',
    fontSize: 19,
    textAlign: 'left',
    textColor: '#1A1414',
    authorColor: '#E4001B',
    textGlow: null,
    textStrokeWidth: 0,
    textStrokeColor: null,
    bubbleBg: 'rgba(255, 255, 255, 0.97)',
    bubbleRadius: 6,
    bubbleOpacity: 1,
    bubbleBorderWidth: 2,
    bubbleBorderStyle: 'solid',
    bubbleBorderColor: '#E4001B',
    bubbleBorderOffset: null,
    bubbleBoxShadow: '0 0 0 1px rgba(228, 0, 27, 0.15)',
    bubbleGlow: null,
    bubblePadding: null,
    bubblePaddingX: 18,
    bubblePaddingY: 8,
    bubblePaddingTop: null,
    bubblePaddingRight: null,
    bubblePaddingBottom: null,
    bubblePaddingLeft: null,
    bubbleTextureUrl: null,
    bubbleTextureSize: 'auto',
    bubbleTextureRepeat: 'repeat',
    bubbleTextureOpacity: 1,
    bubbleBunnyEars: false,
    bubbleBunnyEarsWidth: 32,
    bubbleBunnyEarsHeight: 30,
    bubbleBunnyEarsRoundness: 0,
    bubbleBunnyEarsOffsetX: 20,
    bubbleBunnyEarsOffsetY: 28,
    bubbleBunnyEarsRotate: 0,
    bubbleBunnyEarsZIndex: -1,
    bubbleMinWidth: 0,
    bubbleMaxWidth: 0,
    bubbleFixedWidth: 0,
    bubbleMinHeight: 0,
    bubbleMaxHeight: 0,
    bubbleFixedHeight: 0,
    avatarSize: 30,
    showAvatar: true,
    showBadges: false,
    animationMs: 160,
    position: 'bottom-up',
    maxMessages: 40,
    poolWarmupSize: 20,
    // Ticker — continuous scrolling "breaking news" marquee along the
    // bottom edge instead of stacked bubbles.
    displayMode: 'ticker',
    danmakuSpeed: 1,
    danmakuLanes: 12,
    danmakuAreaTopPct: 4,
    danmakuAreaBottomPct: 4,
    tickerSpeed: 1.2,
    tickerGap: 40,
    tickerPosition: 'bottom',
    // No bob, no shimmer — a news ticker should read as crisp/urgent and
    // legible, not decorative.
    idleAnimation: 'none',
    idleAnimationSpeed: 3,
    idleAnimationIntensity: 5,
    idleShimmerEnabled: false,
    idleShimmerSpeed: 1.8,
    idleShimmerIntensity: 8,
    emojiGlyphEnabled: true,
    emojiGlyphBg: 'rgba(228, 0, 27, 0.12)',
    emojiGlyphRadius: 4,
    emojiGlyphOpacity: 1,
    emojiGlyphGlow: null,
  },
  layoutConfig: defaultLayout(),
  slotStyleConfig: defaultSlotStyle(),
  animationConfig: {
    enabled: true,
    style: 'slideStrong',
    targets: {
      avatar:   { durationMs: null, delayMs: 0, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', translateX: 0, translateY: 0, blur: 0 },
      author:   { durationMs: null, delayMs: 20, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', translateX: -16, translateY: 0, blur: 0 },
      badges:   { durationMs: null, delayMs: 30, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', translateX: -12, translateY: 0, blur: 0 },
      message:  { durationMs: null, delayMs: 40, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', translateX: -10, translateY: 0, blur: 0 },
    },
  },
  decorationConfig: emptyDecorations(),
  roleStyleConfig: {
    roles: {
      moderator: {
      enabled: true,
      authorColor: '#0B5FBF',
      authorBorderColor: 'rgba(11, 95, 191, 0.6)',
      authorBg: null,
      messageBg: 'rgba(235, 243, 255, 0.97)',
      messageBorderColor: 'rgba(11, 95, 191, 0.45)',
      messageTextColor: '#0B3A73',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      showAmount: null,
      authorFontWeight: 'extrabold',
      messageBorderWidth: null,
      textScale: null,
      memberTiers: [],
    },
      member: {
      milestoneLayout: 'highlight',
      enabled: true,
      authorColor: '#9E730A',
      authorBorderColor: 'rgba(184, 134, 11, 0.55)',
      authorBg: null,
      messageBg: 'rgba(255, 248, 230, 0.97)',
      messageBorderColor: 'rgba(184, 134, 11, 0.45)',
      messageTextColor: '#6B4E00',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: '📌',
      badgeAfter: null,
      showAmount: null,
      authorFontWeight: 'bold',
      messageBorderWidth: null,
      textScale: 1.1,
      memberTiers: [
        { id: 'tier-1mo', minMonths: 1, color: '#9E730A', badge: '📌' },
        { id: 'tier-3mo', minMonths: 3, color: '#9C6B00', badge: '📌📌' },
        { id: 'tier-6mo', minMonths: 6, color: '#7A4B00', badge: '📌📌📌' },
        { id: 'tier-12mo', minMonths: 12, color: '#E4001B', badge: '👑' },
      ],
    },
      superchat: {
      enabled: true,
      authorColor: '#FFFFFF',
      authorBorderColor: 'rgba(228, 0, 27, 0.9)',
      authorBg: null,
      messageBg: '#E4001B',
      messageBorderColor: '#E4001B',
      messageTextColor: '#FFFFFF',
      rowBg: '#E4001B',
      rowBorderColor: '#E4001B',
      earColor: null,
      badgeBefore: '🔴',
      badgeAfter: null,
      showAmount: true,
      fontSize: null,
      authorFontWeight: 'extrabold',
      messageBorderWidth: 2,
      textScale: 1.25,
      memberTiers: [],
      useTierColor: false,
      superchatLayout: 'youtube',
      amountFontSize: null,
      amountFontWeight: 'extrabold',
      amountPosition: 'block',
    },
    },
  },
};
