// Theme preset: vtuber-cute

const { defaultLayout, defaultSlotStyle, emptyDecorations, defaultThemeFanService } = require('../helpers');

module.exports = {
  id: 'vtuber-cute',
  name: 'VTuber Cute',
  author: 'built-in',
  version: '1.2.0',
  description: 'Colourful idol-style bubbles with bunny-ear accents and a soft sparkle sweep — Super Chat becomes a full idol spotlight moment.',
  category: 'cute',
  tags: ["vtuber","idol","bunny","cute","colorful"],
  createdAt: '2024-01-01',
  modifiedAt: '2026-08-04',
  customizeConfig: {
    fontFamily: '"Nunito", "M PLUS Rounded 1c", system-ui, sans-serif',
    fontSize: 15,
    textAlign: 'left',
    textColor: '#FFF0F8',
    authorColor: '#FF94CC',
    textGlow: 'drop-shadow(0 1px 3px rgba(40, 10, 50, 0.7))',
    textStrokeWidth: 0,
    textStrokeColor: null,
    bubbleBg: 'rgba(80, 30, 120, 0.92)',
    bubbleRadius: 20,
    bubbleOpacity: 1,
    bubbleBorderWidth: 1,
    bubbleBorderStyle: 'solid',
    bubbleBorderColor: 'rgba(255, 148, 204, 0.4)',
    bubbleBorderOffset: null,
    bubbleBoxShadow: '0 4px 16px rgba(255, 100, 180, 0.18)',
    bubbleGlow: 'drop-shadow(0 0 4px rgba(255, 148, 204, 0.25))',
    bubblePadding: null,
    bubblePaddingX: 14,
    bubblePaddingY: 8,
    bubblePaddingTop: null,
    bubblePaddingRight: null,
    bubblePaddingBottom: null,
    bubblePaddingLeft: null,
    bubbleTextureUrl: null,
    bubbleTextureSize: 'auto',
    bubbleTextureRepeat: 'repeat',
    bubbleTextureOpacity: 1,
    bubbleBunnyEars: true,
    bubbleBunnyEarsWidth: 28,
    bubbleBunnyEarsHeight: 26,
    bubbleBunnyEarsRoundness: 20,
    bubbleBunnyEarsOffsetX: 18,
    bubbleBunnyEarsOffsetY: 24,
    bubbleBunnyEarsRotate: 8,
    bubbleBunnyEarsZIndex: -1,
    bubbleMinWidth: 0,
    bubbleMaxWidth: 0,
    bubbleFixedWidth: 0,
    bubbleMinHeight: 0,
    bubbleMaxHeight: 0,
    bubbleFixedHeight: 0,
    avatarSize: 36,
    showAvatar: true,
    animationMs: 320,
    position: 'bottom-up',
    maxMessages: 35,
    idleAnimation: 'float',
    idleAnimationSpeed: 4,
    idleAnimationIntensity: 6.5,
    idleShimmerEnabled: true,
    idleShimmerSpeed: 3,
    idleShimmerIntensity: 6,
    emojiGlyphEnabled: true,
    emojiGlyphBg: 'rgba(255, 255, 255, 0.1)',
    emojiGlyphRadius: 6,
    emojiGlyphOpacity: 1,
    emojiGlyphGlow: null,
  },
  // Idol nameplate + chat bubble as two separate shapes, name tag tilted
  // slightly for that hand-placed sticker/idol-badge feel.
  layoutConfig: defaultLayout({
    slots: { avatar: { visible: false } },
    screen: { bubbleWrapRow: false, bubbleWrapAuthor: true, bubbleWrapMessage: true },
  }),
  slotStyleConfig: defaultSlotStyle({
    slots: {
      author: {
        bubbleBg: 'rgba(255, 148, 204, 0.95)', bubbleRadius: 999, color: '#5A1240',
        rotate: 3, translateY: -2, zIndex: 2,
        // Split-bubble mode (bọc từng phần): bunny ears stay on the message
        // bubble only, never on the name ribbon.
        bubbleBunnyEars: false,
      },
      message: { bubbleBg: 'rgba(80, 30, 120, 0.85)' },
    },
  }),
  animationConfig: {
    enabled: true,
    style: 'bounce',
    targets: {
      avatar:   { durationMs: null, delayMs: 0, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0, translateY: 16, blur: 0 },
      author:   { durationMs: null, delayMs: 40, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: -12, translateY: 0, blur: 0 },
      message:  { durationMs: null, delayMs: 80, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0, translateY: 12, blur: 0 },
    },
  },
  decorationConfig: emptyDecorations(),
  roleStyleConfig: {
    roles: {
      moderator: {
      enabled: true,
      authorColor: '#FF4D9E',
      authorBorderColor: 'rgba(255, 77, 158, 0.65)',
      authorBg: null,
      messageBg: 'rgba(126, 42, 130, 0.9)',
      messageBorderColor: 'rgba(255, 77, 158, 0.45)',
      messageTextColor: '#FF9AC8',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: null,
      memberTiers: [],
    },
      member: {
      enabled: true,
      authorColor: '#CAB8FC',
      authorBorderColor: 'rgba(167, 139, 250, 0.55)',
      authorBg: null,
      messageBg: 'rgba(117, 76, 175, 0.92)',
      messageBorderColor: 'rgba(167, 139, 250, 0.4)',
      messageTextColor: '#E6DEFE',
      rowBg: null,
      rowBorderColor: null,
      earColor: null,
      badgeBefore: null,
      badgeAfter: null,
      authorFontWeight: null,
      messageBorderWidth: null,
      textScale: 1.15,
      memberTiers: [
        { id: 'tier-1mo', minMonths: 1, color: '#CAB8FC', badge: '✨' },
        { id: 'tier-3mo', minMonths: 3, color: '#FFA8D3', badge: '✨✨' },
        { id: 'tier-6mo', minMonths: 6, color: '#FFA8CF', badge: '🎤' },
        { id: 'tier-12mo', minMonths: 12, color: '#FCD34D', badge: '👑' },
      ],
    },
    },
  },
  fanServiceConfig: defaultThemeFanService({
    superchat: { authorColor: '#FF94CC', messageColor: '#FFF0F8' },
    membership: { authorColor: '#CAB8FC', messageColor: '#E6DEFE', monthsColor: '#CAB8FC' },
  }),
};
