/**
 * theme-presets.js — Built-in Theme Library.
 *
 * Every theme is a plain JavaScript object containing metadata fields and
 * the six configuration categories the app recognises:
 *
 *   Metadata fields:
 *     id, name, author, version, description, category, tags, createdAt,
 *     modifiedAt
 *
 *   Configuration categories:
 *     customizeConfig   — shared/customize-config.js#DEFAULT_CUSTOMIZE_CONFIG
 *     layoutConfig      — shared/layout-config.js#DEFAULT_LAYOUT_CONFIG
 *     slotStyleConfig   — shared/slot-style-config.js#DEFAULT_SLOT_STYLE_CONFIG
 *     animationConfig   — shared/animation-config.js#DEFAULT_ANIMATION_CONFIG
 *     decorationConfig  — shared/decoration-config.js#DEFAULT_DECORATION_CONFIG
 *     roleStyleConfig   — shared/role-style-config.js#DEFAULT_ROLE_STYLE_CONFIG
 *
 * Rules:
 *   - NO DOM, NO rendering logic, NO UI references here.
 *   - Keys must match the exact property names used by the shared configs.
 *   - All six categories must be fully specified on every theme (no partial
 *     overrides) so ThemeManager.NormalizeTheme() can rely on completeness.
 *   - Do NOT hardcode themes anywhere else in the codebase — import from here.
 */

// ---------------------------------------------------------------------------
// Shared role-style helpers
// ---------------------------------------------------------------------------

/** Default role styling (classic dark). */
function defaultRoles() {
  return {
    roles: {
      moderator: {
        enabled: false,
        authorColor: '#fca5a5',
        authorBorderColor: 'rgba(248, 113, 113, 0.7)',
        authorBg: null,
        messageBg: 'linear-gradient(135deg, rgba(248, 113, 113, 0.22), rgba(22, 25, 31, 0.72))',
        messageBorderColor: 'rgba(248, 113, 113, 0.45)',
        messageTextColor: null,
        rowBg: null,
        rowBorderColor: null,
        badgeBefore: 'MOD',
        badgeAfter: null,
        showAmount: null,
      },
      member: {
        enabled: false,
        authorColor: '#93c5fd',
        authorBorderColor: 'rgba(96, 165, 250, 0.55)',
        authorBg: null,
        messageBg: null,
        messageBorderColor: 'rgba(96, 165, 250, 0.45)',
        messageTextColor: null,
        rowBg: null,
        rowBorderColor: null,
        badgeBefore: '★',
        badgeAfter: null,
        showAmount: null,
      },
      superchat: {
        enabled: false,
        authorColor: '#fde047',
        authorBorderColor: 'rgba(255, 202, 40, 0.55)',
        authorBg: null,
        messageBg: 'linear-gradient(135deg, rgba(255, 202, 40, 0.28), rgba(22, 25, 31, 0.72))',
        messageBorderColor: 'rgba(255, 202, 40, 0.45)',
        messageTextColor: null,
        rowBg: 'linear-gradient(135deg, rgba(255, 202, 40, 0.22), rgba(22, 25, 31, 0.72))',
        rowBorderColor: 'rgba(255, 202, 40, 0.45)',
        badgeBefore: '✦',
        badgeAfter: null,
        showAmount: true,
      },
    },
  };
}

/** Default layout (horizontal, avatar-left, message-below). */
function defaultLayout() {
  return {
    messageRow: { direction: 'horizontal', gap: 10, align: 'start', padding: 8, margin: 0 },
    metaRow: { direction: 'horizontal', gap: 6, align: 'center', padding: 0, margin: 2 },
    bodyColumn: { direction: 'vertical', gap: 2, align: 'stretch', padding: 0, margin: 0 },
    slots: {
      avatar: { order: 0, padding: 0, margin: 0, visible: null, position: 'static', top: null, left: null, right: null, bottom: null, zIndex: null },
      author: { order: 0, padding: 0, margin: 0, visible: null, position: 'static', top: null, left: null, right: null, bottom: null, zIndex: null },
      badges: { order: 1, padding: 0, margin: 0, visible: null, position: 'static', top: null, left: null, right: null, bottom: null, zIndex: null },
      message: { order: 1, padding: 0, margin: 0, visible: null, position: 'static', top: null, left: null, right: null, bottom: null, zIndex: null },
    },
    screen: {
      chatAlign: 'left',
      contentDirection: 'ltr',
      chatGap: 10,
      bubbleScope: null,
      bubbleWrapRow: true,
      bubbleWrapAuthor: false,
      bubbleWrapMessage: false,
    },
  };
}

/** Default slot-style (all nulls → inherits from customizeConfig). */
function defaultSlotStyle() {
  return {
    slots: {
      avatar: {
        visible: null, size: null, borderRadius: null, borderWidth: null,
        borderStyle: null, borderColor: null, borderOffset: null,
        opacity: null, margin: 0,
        rotate: 0, translateX: 0, translateY: 0, transformOrigin: null, zIndex: null,
      },
      author: {
        visible: null, fontFamily: null, fontSize: null, color: null,
        fontWeight: null, opacity: null, margin: 0, textAlign: null,
        rotate: 0, translateX: 0, translateY: 0, transformOrigin: null, zIndex: null,
        bubbleBg: null, bubbleRadius: null, bubbleOpacity: null, bubbleBorderWidth: null,
        bubbleBorderStyle: null, bubbleBorderColor: null, bubbleBorderOffset: null,
        bubbleBoxShadow: null, bubbleGlow: null, bubblePadding: null,
        bubblePaddingX: null, bubblePaddingY: null, bubblePaddingTop: null,
        bubblePaddingRight: null, bubblePaddingBottom: null, bubblePaddingLeft: null,
        bubbleTextureUrl: null, bubbleTextureSize: 'auto', bubbleTextureRepeat: 'repeat',
        bubbleTextureOpacity: 1, bubbleBunnyEars: null, bubbleBunnyEarsWidth: null,
        bubbleBunnyEarsHeight: null, bubbleBunnyEarsRoundness: null, bubbleBunnyEarsOffsetX: null,
        bubbleBunnyEarsOffsetY: null, bubbleBunnyEarsZIndex: null, bubbleMinWidth: null,
        bubbleMaxWidth: null, bubbleFixedWidth: null,
        bubbleMinHeight: null, bubbleMaxHeight: null, bubbleFixedHeight: null,
      },
      badges: {
        visible: null, fontSize: null, opacity: null, margin: 0,
        rotate: 0, translateX: 0, translateY: 0, transformOrigin: null, zIndex: null,
      },
      message: {
        visible: null, fontFamily: null, fontSize: null, color: null,
        fontWeight: null, opacity: null, margin: 0, textAlign: null,
        rotate: 0, translateX: 0, translateY: 0, transformOrigin: null, zIndex: null,
        bubbleBg: null, bubbleRadius: null, bubbleOpacity: null, bubbleBorderWidth: null,
        bubbleBorderStyle: null, bubbleBorderColor: null, bubbleBorderOffset: null,
        bubbleBoxShadow: null, bubbleGlow: null, bubblePadding: null,
        bubblePaddingX: null, bubblePaddingY: null, bubblePaddingTop: null,
        bubblePaddingRight: null, bubblePaddingBottom: null, bubblePaddingLeft: null,
        bubbleTextureUrl: null, bubbleTextureSize: 'auto', bubbleTextureRepeat: 'repeat',
        bubbleTextureOpacity: 1, bubbleBunnyEars: null, bubbleBunnyEarsWidth: null,
        bubbleBunnyEarsHeight: null, bubbleBunnyEarsRoundness: null, bubbleBunnyEarsOffsetX: null,
        bubbleBunnyEarsOffsetY: null, bubbleBunnyEarsZIndex: null, bubbleMinWidth: null,
        bubbleMaxWidth: null, bubbleFixedWidth: null,
        bubbleMinHeight: null, bubbleMaxHeight: null, bubbleFixedHeight: null,
      },
    },
  };
}

/** Default animation (slide, bottom-up stagger). */
function defaultAnimation() {
  return {
    enabled: true,
    style: 'slide',
    targets: {
      avatar:  { durationMs: null, delayMs: 0,  easing: 'ease-out', translateX: 0,  translateY: 8, scale: 1, blur: 0 },
      author:  { durationMs: null, delayMs: 40, easing: 'ease-out', translateX: -6, translateY: 0, scale: 1, blur: 0 },
      badges:  { durationMs: null, delayMs: 60, easing: 'ease-out', translateX: -4, translateY: 0, scale: 1, blur: 0 },
      message: { durationMs: null, delayMs: 80, easing: 'ease-out', translateX: 0,  translateY: 6, scale: 1, blur: 0 },
    },
  };
}

/** No decoration layers. */
function emptyDecorations() {
  return { layers: [] };
}

// ---------------------------------------------------------------------------
// Theme definitions
// ---------------------------------------------------------------------------

const BUILTIN_THEMES = [

  // ── Default ────────────────────────────────────────────────────────────────
  {
    id: 'default',
    name: 'Default',
    author: 'built-in',
    version: '1.0.0',
    description: 'The standard dark-panel look shipped with YouTube Overlay Studio.',
    category: 'dark',
    tags: ['dark', 'clean', 'default'],
    createdAt: '2024-01-01',
    modifiedAt: '2024-01-01',
    customizeConfig: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: 16,
      textColor: '#EAECEF',
      authorColor: '#6E56F0',
      bubbleBg: 'rgba(22, 25, 31, 0.72)',
      bubbleRadius: 14,
      bubbleOpacity: 1,
      bubbleBorderWidth: null,
      bubbleBorderStyle: null,
      bubbleBorderColor: null,
      bubbleBoxShadow: null,
      bubbleGlow: null,
      bubblePadding: null,
      bubblePaddingX: null,
      bubblePaddingY: null,
      bubblePaddingTop: null,
      bubblePaddingRight: null,
      bubblePaddingBottom: null,
      bubblePaddingLeft: null,
      bubbleTextureUrl: null,
      bubbleTextureSize: 'auto',
      bubbleTextureRepeat: 'repeat',
      bubbleTextureOpacity: 1,
      bubbleBunnyEars: false,
      bubbleBunnyEarsWidth: 32,
      bubbleBunnyEarsHeight: 30,
      bubbleBunnyEarsRoundness: 0,
      bubbleBunnyEarsOffsetX: 20,
      bubbleBunnyEarsOffsetY: 28,
      bubbleBunnyEarsRotate: 0,
      bubbleBunnyEarsZIndex: -1,
      bubbleMinWidth: 0,
      bubbleMaxWidth: 0,
      bubbleFixedWidth: 0,
      bubbleMinHeight: 0,
      bubbleMaxHeight: 0,
      bubbleFixedHeight: 0,
      avatarSize: 32,
      showAvatar: true,
      showBadges: true,
      animationMs: 220,
      position: 'bottom-up',
      maxMessages: 40,
    },
    layoutConfig: defaultLayout(),
    slotStyleConfig: defaultSlotStyle(),
    animationConfig: defaultAnimation(),
    decorationConfig: emptyDecorations(),
    roleStyleConfig: defaultRoles(),
  },

  // ── Minimal White ──────────────────────────────────────────────────────────
  {
    id: 'minimal-white',
    name: 'Minimal White',
    author: 'built-in',
    version: '1.0.0',
    description: 'Clean white text with no bubble background — perfect for bright stream scenes.',
    category: 'minimal',
    tags: ['minimal', 'light', 'clean'],
    createdAt: '2024-01-01',
    modifiedAt: '2024-01-01',
    customizeConfig: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: 15,
      textColor: '#FFFFFF',
      authorColor: '#3B82F6',
      bubbleBg: 'rgba(0, 0, 0, 0)',
      bubbleRadius: 0,
      bubbleOpacity: 1,
      bubbleBorderWidth: null,
      bubbleBorderStyle: null,
      bubbleBorderColor: null,
      bubbleBoxShadow: null,
      bubbleGlow: null,
      bubblePadding: null,
      bubblePaddingX: null,
      bubblePaddingY: null,
      bubblePaddingTop: null,
      bubblePaddingRight: null,
      bubblePaddingBottom: null,
      bubblePaddingLeft: null,
      bubbleTextureUrl: null,
      bubbleTextureSize: 'auto',
      bubbleTextureRepeat: 'repeat',
      bubbleTextureOpacity: 1,
      bubbleBunnyEars: false,
      bubbleBunnyEarsWidth: 32,
      bubbleBunnyEarsHeight: 30,
      bubbleBunnyEarsRoundness: 0,
      bubbleBunnyEarsOffsetX: 20,
      bubbleBunnyEarsOffsetY: 28,
      bubbleBunnyEarsRotate: 0,
      bubbleBunnyEarsZIndex: -1,
      bubbleMinWidth: 0,
      bubbleMaxWidth: 0,
      bubbleFixedWidth: 0,
      bubbleMinHeight: 0,
      bubbleMaxHeight: 0,
      bubbleFixedHeight: 0,
      avatarSize: 24,
      showAvatar: false,
      showBadges: false,
      animationMs: 160,
      position: 'bottom-up',
      maxMessages: 30,
    },
    layoutConfig: defaultLayout(),
    slotStyleConfig: defaultSlotStyle(),
    animationConfig: { ...defaultAnimation(), style: 'slide' },
    decorationConfig: emptyDecorations(),
    roleStyleConfig: {
      roles: {
        moderator: { ...defaultRoles().roles.moderator, authorColor: '#F87171', messageBg: null, messageBorderColor: null },
        member: { ...defaultRoles().roles.member, authorColor: '#60A5FA', messageBorderColor: null },
        superchat: { ...defaultRoles().roles.superchat, authorColor: '#FACC15', messageBg: null, rowBg: null },
      },
    },
  },

  // ── Minimal Dark ───────────────────────────────────────────────────────────
  {
    id: 'minimal-dark',
    name: 'Minimal Dark',
    author: 'built-in',
    version: '1.0.0',
    description: 'Transparent bubble, light-grey text — ideal for dark stream scenes.',
    category: 'minimal',
    tags: ['minimal', 'dark', 'clean'],
    createdAt: '2024-01-01',
    modifiedAt: '2024-01-01',
    customizeConfig: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: 15,
      textColor: '#EAECEF',
      authorColor: '#6E56F0',
      bubbleBg: 'rgba(0, 0, 0, 0)',
      bubbleRadius: 0,
      bubbleOpacity: 1,
      bubbleBorderWidth: null,
      bubbleBorderStyle: null,
      bubbleBorderColor: null,
      bubbleBoxShadow: null,
      bubbleGlow: null,
      bubblePadding: null,
      bubblePaddingX: null,
      bubblePaddingY: null,
      bubblePaddingTop: null,
      bubblePaddingRight: null,
      bubblePaddingBottom: null,
      bubblePaddingLeft: null,
      bubbleTextureUrl: null,
      bubbleTextureSize: 'auto',
      bubbleTextureRepeat: 'repeat',
      bubbleTextureOpacity: 1,
      bubbleBunnyEars: false,
      bubbleBunnyEarsWidth: 32,
      bubbleBunnyEarsHeight: 30,
      bubbleBunnyEarsRoundness: 0,
      bubbleBunnyEarsOffsetX: 20,
      bubbleBunnyEarsOffsetY: 28,
      bubbleBunnyEarsRotate: 0,
      bubbleBunnyEarsZIndex: -1,
      bubbleMinWidth: 0,
      bubbleMaxWidth: 0,
      bubbleFixedWidth: 0,
      bubbleMinHeight: 0,
      bubbleMaxHeight: 0,
      bubbleFixedHeight: 0,
      avatarSize: 24,
      showAvatar: false,
      showBadges: false,
      animationMs: 160,
      position: 'bottom-up',
      maxMessages: 30,
    },
    layoutConfig: defaultLayout(),
    slotStyleConfig: defaultSlotStyle(),
    animationConfig: { ...defaultAnimation(), style: 'slide' },
    decorationConfig: emptyDecorations(),
    roleStyleConfig: defaultRoles(),
  },

  // ── Discord ────────────────────────────────────────────────────────────────
  {
    id: 'discord',
    name: 'Discord',
    author: 'built-in',
    version: '1.0.0',
    description: 'Familiar Discord-style dark panel with Blurple accents.',
    category: 'dark',
    tags: ['dark', 'discord', 'blurple'],
    createdAt: '2024-01-01',
    modifiedAt: '2024-01-01',
    customizeConfig: {
      fontFamily: '"Whitney", "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: 15,
      textColor: '#DCDDDE',
      authorColor: '#7289DA',
      bubbleBg: 'rgba(47, 49, 54, 0.90)',
      bubbleRadius: 8,
      bubbleOpacity: 1,
      bubbleBorderWidth: null,
      bubbleBorderStyle: null,
      bubbleBorderColor: null,
      bubbleBoxShadow: '0 2px 8px rgba(0,0,0,0.35)',
      bubbleGlow: null,
      bubblePadding: null,
      bubblePaddingX: 14,
      bubblePaddingY: 8,
      bubblePaddingTop: null,
      bubblePaddingRight: null,
      bubblePaddingBottom: null,
      bubblePaddingLeft: null,
      bubbleTextureUrl: null,
      bubbleTextureSize: 'auto',
      bubbleTextureRepeat: 'repeat',
      bubbleTextureOpacity: 1,
      bubbleBunnyEars: false,
      bubbleBunnyEarsWidth: 32,
      bubbleBunnyEarsHeight: 30,
      bubbleBunnyEarsRoundness: 0,
      bubbleBunnyEarsOffsetX: 20,
      bubbleBunnyEarsOffsetY: 28,
      bubbleBunnyEarsRotate: 0,
      bubbleBunnyEarsZIndex: -1,
      bubbleMinWidth: 0,
      bubbleMaxWidth: 0,
      bubbleFixedWidth: 0,
      bubbleMinHeight: 0,
      bubbleMaxHeight: 0,
      bubbleFixedHeight: 0,
      avatarSize: 36,
      showAvatar: true,
      showBadges: true,
      animationMs: 180,
      position: 'bottom-up',
      maxMessages: 35,
    },
    layoutConfig: defaultLayout(),
    slotStyleConfig: defaultSlotStyle(),
    animationConfig: { ...defaultAnimation(), style: 'slide' },
    decorationConfig: emptyDecorations(),
    roleStyleConfig: {
      roles: {
        moderator: { ...defaultRoles().roles.moderator, authorColor: '#43B581', authorBorderColor: 'rgba(67, 181, 129, 0.6)', messageBg: 'linear-gradient(135deg, rgba(67, 181, 129, 0.15), rgba(47, 49, 54, 0.90))', messageBorderColor: 'rgba(67, 181, 129, 0.4)', badgeBefore: 'MOD' },
        member: { ...defaultRoles().roles.member },
        superchat: { ...defaultRoles().roles.superchat },
      },
    },
  },

  // ── Cyber Neon ─────────────────────────────────────────────────────────────
  {
    id: 'cyber-neon',
    name: 'Cyber Neon',
    author: 'built-in',
    version: '1.0.0',
    description: 'Dark cyberpunk theme with electric-cyan highlights and monospace font.',
    category: 'gaming',
    tags: ['dark', 'cyberpunk', 'neon', 'gaming'],
    createdAt: '2024-01-01',
    modifiedAt: '2024-01-01',
    customizeConfig: {
      fontFamily: 'ui-monospace, "JetBrains Mono", "Fira Code", monospace',
      fontSize: 14,
      textColor: '#D8FCFF',
      authorColor: '#00E5FF',
      bubbleBg: 'rgba(6, 10, 18, 0.85)',
      bubbleRadius: 4,
      bubbleOpacity: 1,
      bubbleBorderWidth: 1,
      bubbleBorderStyle: 'solid',
      bubbleBorderColor: 'rgba(0, 229, 255, 0.35)',
      bubbleBoxShadow: '0 0 8px rgba(0, 229, 255, 0.15)',
      bubbleGlow: 'drop-shadow(0 0 4px rgba(0, 229, 255, 0.4))',
      bubblePadding: null,
      bubblePaddingX: 12,
      bubblePaddingY: 6,
      bubblePaddingTop: null,
      bubblePaddingRight: null,
      bubblePaddingBottom: null,
      bubblePaddingLeft: null,
      bubbleTextureUrl: null,
      bubbleTextureSize: 'auto',
      bubbleTextureRepeat: 'repeat',
      bubbleTextureOpacity: 1,
      bubbleBunnyEars: false,
      bubbleBunnyEarsWidth: 32,
      bubbleBunnyEarsHeight: 30,
      bubbleBunnyEarsRoundness: 0,
      bubbleBunnyEarsOffsetX: 20,
      bubbleBunnyEarsOffsetY: 28,
      bubbleBunnyEarsRotate: 0,
      bubbleBunnyEarsZIndex: -1,
      bubbleMinWidth: 0,
      bubbleMaxWidth: 0,
      bubbleFixedWidth: 0,
      bubbleMinHeight: 0,
      bubbleMaxHeight: 0,
      bubbleFixedHeight: 0,
      avatarSize: 28,
      showAvatar: true,
      showBadges: true,
      animationMs: 180,
      position: 'bottom-up',
      maxMessages: 40,
    },
    layoutConfig: defaultLayout(),
    slotStyleConfig: defaultSlotStyle(),
    animationConfig: {
      enabled: true,
      style: 'slideStrong',
      targets: {
        avatar:  { durationMs: null, delayMs: 0,  easing: 'cubic-bezier(0.16, 1, 0.3, 1)', translateX: 0,   translateY: 48, scale: 1, blur: 0 },
        author:  { durationMs: null, delayMs: 40, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', translateX: -36, translateY: 0,  scale: 1, blur: 0 },
        badges:  { durationMs: null, delayMs: 60, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', translateX: -24, translateY: 0,  scale: 1, blur: 0 },
        message: { durationMs: null, delayMs: 80, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', translateX: 0,   translateY: 36, scale: 1, blur: 0 },
      },
    },
    decorationConfig: emptyDecorations(),
    roleStyleConfig: {
      roles: {
        moderator: { enabled: false, authorColor: '#FF4081', authorBorderColor: 'rgba(255, 64, 129, 0.7)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(255, 64, 129, 0.18), rgba(6, 10, 18, 0.85))', messageBorderColor: 'rgba(255, 64, 129, 0.45)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: 'MOD', badgeAfter: null, showAmount: null },
        member: { enabled: false, authorColor: '#69F0AE', authorBorderColor: 'rgba(105, 240, 174, 0.55)', authorBg: null, messageBg: null, messageBorderColor: 'rgba(105, 240, 174, 0.4)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '★', badgeAfter: null, showAmount: null },
        superchat: { enabled: false, authorColor: '#FFEB3B', authorBorderColor: 'rgba(255, 235, 59, 0.6)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(255, 235, 59, 0.22), rgba(6, 10, 18, 0.85))', messageBorderColor: 'rgba(255, 235, 59, 0.4)', messageTextColor: null, rowBg: 'linear-gradient(135deg, rgba(255, 235, 59, 0.15), rgba(6, 10, 18, 0.85))', rowBorderColor: 'rgba(255, 235, 59, 0.4)', badgeBefore: '✦', badgeAfter: null, showAmount: true },
      },
    },
  },

  // ── Pastel Pink ────────────────────────────────────────────────────────────
  {
    id: 'pastel-pink',
    name: 'Pastel Pink',
    author: 'built-in',
    version: '1.0.0',
    description: 'Soft pink bubbles with warm purple author names.',
    category: 'cute',
    tags: ['cute', 'pink', 'pastel', 'soft'],
    createdAt: '2024-01-01',
    modifiedAt: '2024-01-01',
    customizeConfig: {
      fontFamily: '"Nunito", "Varela Round", system-ui, sans-serif',
      fontSize: 15,
      textColor: '#4A2E4E',
      authorColor: '#C45594',
      bubbleBg: 'rgba(255, 214, 234, 0.75)',
      bubbleRadius: 18,
      bubbleOpacity: 1,
      bubbleBorderWidth: 1,
      bubbleBorderStyle: 'solid',
      bubbleBorderColor: 'rgba(196, 85, 148, 0.25)',
      bubbleBoxShadow: '0 2px 12px rgba(196, 85, 148, 0.12)',
      bubbleGlow: null,
      bubblePadding: null,
      bubblePaddingX: 14,
      bubblePaddingY: 8,
      bubblePaddingTop: null,
      bubblePaddingRight: null,
      bubblePaddingBottom: null,
      bubblePaddingLeft: null,
      bubbleTextureUrl: null,
      bubbleTextureSize: 'auto',
      bubbleTextureRepeat: 'repeat',
      bubbleTextureOpacity: 1,
      bubbleBunnyEars: false,
      bubbleBunnyEarsWidth: 32,
      bubbleBunnyEarsHeight: 30,
      bubbleBunnyEarsRoundness: 0,
      bubbleBunnyEarsOffsetX: 20,
      bubbleBunnyEarsOffsetY: 28,
      bubbleBunnyEarsRotate: 0,
      bubbleBunnyEarsZIndex: -1,
      bubbleMinWidth: 0,
      bubbleMaxWidth: 0,
      bubbleFixedWidth: 0,
      bubbleMinHeight: 0,
      bubbleMaxHeight: 0,
      bubbleFixedHeight: 0,
      avatarSize: 30,
      showAvatar: true,
      showBadges: true,
      animationMs: 280,
      position: 'bottom-up',
      maxMessages: 35,
    },
    layoutConfig: defaultLayout(),
    slotStyleConfig: defaultSlotStyle(),
    animationConfig: {
      enabled: true,
      style: 'bounce',
      targets: {
        avatar:  { durationMs: null, delayMs: 0,  easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0,   translateY: 16, scale: 0.85, blur: 0 },
        author:  { durationMs: null, delayMs: 40, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: -12, translateY: 0,  scale: 0.85, blur: 0 },
        badges:  { durationMs: null, delayMs: 60, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: -8,  translateY: 0,  scale: 0.85, blur: 0 },
        message: { durationMs: null, delayMs: 80, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0,   translateY: 12, scale: 0.85, blur: 0 },
      },
    },
    decorationConfig: emptyDecorations(),
    roleStyleConfig: {
      roles: {
        moderator: { enabled: false, authorColor: '#E91E8C', authorBorderColor: 'rgba(233, 30, 140, 0.6)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(233, 30, 140, 0.15), rgba(255, 214, 234, 0.75))', messageBorderColor: 'rgba(233, 30, 140, 0.35)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: 'MOD', badgeAfter: null, showAmount: null },
        member: { enabled: false, authorColor: '#7B68EE', authorBorderColor: 'rgba(123, 104, 238, 0.5)', authorBg: null, messageBg: null, messageBorderColor: 'rgba(123, 104, 238, 0.35)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '★', badgeAfter: null, showAmount: null },
        superchat: { enabled: false, authorColor: '#FF8C00', authorBorderColor: 'rgba(255, 140, 0, 0.55)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(255, 140, 0, 0.2), rgba(255, 214, 234, 0.75))', messageBorderColor: 'rgba(255, 140, 0, 0.4)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '✦', badgeAfter: null, showAmount: true },
      },
    },
  },

  // ── Glassmorphism ──────────────────────────────────────────────────────────
  {
    id: 'glassmorphism',
    name: 'Glassmorphism',
    author: 'built-in',
    version: '1.0.0',
    description: 'Frosted-glass effect with a translucent white panel and soft borders.',
    category: 'colorful',
    tags: ['glass', 'blur', 'frosted', 'translucent'],
    createdAt: '2024-01-01',
    modifiedAt: '2024-01-01',
    customizeConfig: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: 15,
      textColor: '#F2F6FA',
      authorColor: '#8FD3FF',
      bubbleBg: 'rgba(255, 255, 255, 0.10)',
      bubbleRadius: 16,
      bubbleOpacity: 1,
      bubbleBorderWidth: 1,
      bubbleBorderStyle: 'solid',
      bubbleBorderColor: 'rgba(255, 255, 255, 0.25)',
      bubbleBoxShadow: '0 4px 24px rgba(0, 0, 0, 0.18), inset 0 1px 0 rgba(255, 255, 255, 0.18)',
      bubbleGlow: null,
      bubblePadding: null,
      bubblePaddingX: 14,
      bubblePaddingY: 8,
      bubblePaddingTop: null,
      bubblePaddingRight: null,
      bubblePaddingBottom: null,
      bubblePaddingLeft: null,
      bubbleTextureUrl: null,
      bubbleTextureSize: 'auto',
      bubbleTextureRepeat: 'repeat',
      bubbleTextureOpacity: 1,
      bubbleBunnyEars: false,
      bubbleBunnyEarsWidth: 32,
      bubbleBunnyEarsHeight: 30,
      bubbleBunnyEarsRoundness: 0,
      bubbleBunnyEarsOffsetX: 20,
      bubbleBunnyEarsOffsetY: 28,
      bubbleBunnyEarsRotate: 0,
      bubbleBunnyEarsZIndex: -1,
      bubbleMinWidth: 0,
      bubbleMaxWidth: 0,
      bubbleFixedWidth: 0,
      bubbleMinHeight: 0,
      bubbleMaxHeight: 0,
      bubbleFixedHeight: 0,
      avatarSize: 32,
      showAvatar: true,
      showBadges: true,
      animationMs: 240,
      position: 'bottom-up',
      maxMessages: 40,
    },
    layoutConfig: defaultLayout(),
    slotStyleConfig: defaultSlotStyle(),
    animationConfig: {
      enabled: true,
      style: 'blurZoom',
      targets: {
        avatar:  { durationMs: null, delayMs: 0,  easing: 'ease-out', translateX: 0, translateY: 0, scale: 1.08, blur: 10 },
        author:  { durationMs: null, delayMs: 40, easing: 'ease-out', translateX: 0, translateY: 0, scale: 1.08, blur: 10 },
        badges:  { durationMs: null, delayMs: 60, easing: 'ease-out', translateX: 0, translateY: 0, scale: 1.08, blur: 10 },
        message: { durationMs: null, delayMs: 80, easing: 'ease-out', translateX: 0, translateY: 0, scale: 1.08, blur: 10 },
      },
    },
    decorationConfig: emptyDecorations(),
    roleStyleConfig: {
      roles: {
        moderator: { enabled: false, authorColor: '#FF8A80', authorBorderColor: 'rgba(255, 138, 128, 0.6)', authorBg: null, messageBg: 'rgba(255, 138, 128, 0.12)', messageBorderColor: 'rgba(255, 138, 128, 0.4)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: 'MOD', badgeAfter: null, showAmount: null },
        member: { enabled: false, authorColor: '#80D8FF', authorBorderColor: 'rgba(128, 216, 255, 0.5)', authorBg: null, messageBg: null, messageBorderColor: 'rgba(128, 216, 255, 0.35)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '★', badgeAfter: null, showAmount: null },
        superchat: { enabled: false, authorColor: '#FFD740', authorBorderColor: 'rgba(255, 215, 64, 0.55)', authorBg: null, messageBg: 'rgba(255, 215, 64, 0.15)', messageBorderColor: 'rgba(255, 215, 64, 0.4)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '✦', badgeAfter: null, showAmount: true },
      },
    },
  },

  // ── Cute Bubble ────────────────────────────────────────────────────────────
  {
    id: 'cute-bubble',
    name: 'Cute Bubble',
    author: 'built-in',
    version: '1.0.0',
    description: 'Round, colourful speech bubbles with a playful bounce entrance.',
    category: 'cute',
    tags: ['cute', 'bubble', 'round', 'colorful'],
    createdAt: '2024-01-01',
    modifiedAt: '2024-01-01',
    customizeConfig: {
      fontFamily: '"Nunito", "Quicksand", system-ui, sans-serif',
      fontSize: 15,
      textColor: '#FFFFFF',
      authorColor: '#FF6FA5',
      bubbleBg: 'rgba(110, 60, 220, 0.72)',
      bubbleRadius: 999,
      bubbleOpacity: 1,
      bubbleBorderWidth: 2,
      bubbleBorderStyle: 'solid',
      bubbleBorderColor: 'rgba(255, 255, 255, 0.25)',
      bubbleBoxShadow: '0 4px 14px rgba(110, 60, 220, 0.35)',
      bubbleGlow: null,
      bubblePadding: null,
      bubblePaddingX: 18,
      bubblePaddingY: 8,
      bubblePaddingTop: null,
      bubblePaddingRight: null,
      bubblePaddingBottom: null,
      bubblePaddingLeft: null,
      bubbleTextureUrl: null,
      bubbleTextureSize: 'auto',
      bubbleTextureRepeat: 'repeat',
      bubbleTextureOpacity: 1,
      bubbleBunnyEars: false,
      bubbleBunnyEarsWidth: 32,
      bubbleBunnyEarsHeight: 30,
      bubbleBunnyEarsRoundness: 0,
      bubbleBunnyEarsOffsetX: 20,
      bubbleBunnyEarsOffsetY: 28,
      bubbleBunnyEarsRotate: 0,
      bubbleBunnyEarsZIndex: -1,
      bubbleMinWidth: 0,
      bubbleMaxWidth: 0,
      bubbleFixedWidth: 0,
      bubbleMinHeight: 0,
      bubbleMaxHeight: 0,
      bubbleFixedHeight: 0,
      avatarSize: 34,
      showAvatar: true,
      showBadges: true,
      animationMs: 300,
      position: 'bottom-up',
      maxMessages: 35,
    },
    layoutConfig: defaultLayout(),
    slotStyleConfig: defaultSlotStyle(),
    animationConfig: {
      enabled: true,
      style: 'bounce',
      targets: {
        avatar:  { durationMs: null, delayMs: 0,  easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0,   translateY: 16, scale: 0.85, blur: 0 },
        author:  { durationMs: null, delayMs: 40, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: -12, translateY: 0,  scale: 0.85, blur: 0 },
        badges:  { durationMs: null, delayMs: 60, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: -8,  translateY: 0,  scale: 0.85, blur: 0 },
        message: { durationMs: null, delayMs: 80, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0,   translateY: 12, scale: 0.85, blur: 0 },
      },
    },
    decorationConfig: emptyDecorations(),
    roleStyleConfig: {
      roles: {
        moderator: { enabled: false, authorColor: '#FF4081', authorBorderColor: 'rgba(255, 64, 129, 0.6)', authorBg: null, messageBg: 'rgba(255, 64, 129, 0.20)', messageBorderColor: 'rgba(255, 64, 129, 0.45)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: 'MOD', badgeAfter: null, showAmount: null },
        member: { enabled: false, authorColor: '#69F0AE', authorBorderColor: 'rgba(105, 240, 174, 0.55)', authorBg: null, messageBg: null, messageBorderColor: 'rgba(105, 240, 174, 0.4)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '★', badgeAfter: null, showAmount: null },
        superchat: { enabled: false, authorColor: '#FFEB3B', authorBorderColor: 'rgba(255, 235, 59, 0.6)', authorBg: null, messageBg: 'rgba(255, 235, 59, 0.20)', messageBorderColor: 'rgba(255, 235, 59, 0.4)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '✦', badgeAfter: null, showAmount: true },
      },
    },
  },

  // ── Anime ──────────────────────────────────────────────────────────────────
  {
    id: 'anime',
    name: 'Anime',
    author: 'built-in',
    version: '1.0.0',
    description: 'Warm sakura-pink bubbles with manga-style round corners and soft text.',
    category: 'cute',
    tags: ['anime', 'sakura', 'manga', 'pink'],
    createdAt: '2024-01-01',
    modifiedAt: '2024-01-01',
    customizeConfig: {
      fontFamily: '"Segoe UI", system-ui, sans-serif',
      fontSize: 15,
      textColor: '#4A2E4E',
      authorColor: '#FF7EC9',
      bubbleBg: 'rgba(255, 200, 230, 0.65)',
      bubbleRadius: 22,
      bubbleOpacity: 1,
      bubbleBorderWidth: 1,
      bubbleBorderStyle: 'solid',
      bubbleBorderColor: 'rgba(255, 100, 180, 0.3)',
      bubbleBoxShadow: '0 2px 12px rgba(255, 100, 180, 0.15)',
      bubbleGlow: null,
      bubblePadding: null,
      bubblePaddingX: 14,
      bubblePaddingY: 8,
      bubblePaddingTop: null,
      bubblePaddingRight: null,
      bubblePaddingBottom: null,
      bubblePaddingLeft: null,
      bubbleTextureUrl: null,
      bubbleTextureSize: 'auto',
      bubbleTextureRepeat: 'repeat',
      bubbleTextureOpacity: 1,
      bubbleBunnyEars: false,
      bubbleBunnyEarsWidth: 32,
      bubbleBunnyEarsHeight: 30,
      bubbleBunnyEarsRoundness: 0,
      bubbleBunnyEarsOffsetX: 20,
      bubbleBunnyEarsOffsetY: 28,
      bubbleBunnyEarsRotate: 0,
      bubbleBunnyEarsZIndex: -1,
      bubbleMinWidth: 0,
      bubbleMaxWidth: 0,
      bubbleFixedWidth: 0,
      bubbleMinHeight: 0,
      bubbleMaxHeight: 0,
      bubbleFixedHeight: 0,
      avatarSize: 34,
      showAvatar: true,
      showBadges: true,
      animationMs: 320,
      position: 'bottom-up',
      maxMessages: 40,
    },
    layoutConfig: defaultLayout(),
    slotStyleConfig: defaultSlotStyle(),
    animationConfig: {
      enabled: true,
      style: 'bounce',
      targets: {
        avatar:  { durationMs: null, delayMs: 0,  easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0,   translateY: 16, scale: 0.85, blur: 0 },
        author:  { durationMs: null, delayMs: 40, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: -12, translateY: 0,  scale: 0.85, blur: 0 },
        badges:  { durationMs: null, delayMs: 60, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: -8,  translateY: 0,  scale: 0.85, blur: 0 },
        message: { durationMs: null, delayMs: 80, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0,   translateY: 12, scale: 0.85, blur: 0 },
      },
    },
    decorationConfig: emptyDecorations(),
    roleStyleConfig: {
      roles: {
        moderator: { enabled: false, authorColor: '#FF2D78', authorBorderColor: 'rgba(255, 45, 120, 0.6)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(255, 45, 120, 0.18), rgba(255, 200, 230, 0.65))', messageBorderColor: 'rgba(255, 45, 120, 0.4)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: 'MOD', badgeAfter: null, showAmount: null },
        member: { enabled: false, authorColor: '#8B5CF6', authorBorderColor: 'rgba(139, 92, 246, 0.55)', authorBg: null, messageBg: null, messageBorderColor: 'rgba(139, 92, 246, 0.4)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '★', badgeAfter: null, showAmount: null },
        superchat: { enabled: false, authorColor: '#F59E0B', authorBorderColor: 'rgba(245, 158, 11, 0.55)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(245, 158, 11, 0.2), rgba(255, 200, 230, 0.65))', messageBorderColor: 'rgba(245, 158, 11, 0.4)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '✦', badgeAfter: null, showAmount: true },
      },
    },
  },

  // ── VTuber Cute ────────────────────────────────────────────────────────────
  {
    id: 'vtuber-cute',
    name: 'VTuber Cute',
    author: 'built-in',
    version: '1.0.0',
    description: 'Colourful idol-style bubbles with bright gradients and bunny-ear accents.',
    category: 'cute',
    tags: ['vtuber', 'idol', 'bunny', 'cute', 'colorful'],
    createdAt: '2024-01-01',
    modifiedAt: '2024-01-01',
    customizeConfig: {
      fontFamily: '"Nunito", "M PLUS Rounded 1c", system-ui, sans-serif',
      fontSize: 15,
      textColor: '#FFF0F8',
      authorColor: '#FF94CC',
      bubbleBg: 'rgba(80, 30, 120, 0.78)',
      bubbleRadius: 20,
      bubbleOpacity: 1,
      bubbleBorderWidth: 1,
      bubbleBorderStyle: 'solid',
      bubbleBorderColor: 'rgba(255, 148, 204, 0.35)',
      bubbleBoxShadow: '0 4px 16px rgba(255, 100, 180, 0.25)',
      bubbleGlow: 'drop-shadow(0 0 6px rgba(255, 148, 204, 0.3))',
      bubblePadding: null,
      bubblePaddingX: 14,
      bubblePaddingY: 8,
      bubblePaddingTop: null,
      bubblePaddingRight: null,
      bubblePaddingBottom: null,
      bubblePaddingLeft: null,
      bubbleTextureUrl: null,
      bubbleTextureSize: 'auto',
      bubbleTextureRepeat: 'repeat',
      bubbleTextureOpacity: 1,
      bubbleBunnyEars: true,
      bubbleBunnyEarsWidth: 28,
      bubbleBunnyEarsHeight: 26,
      bubbleBunnyEarsRoundness: 20,
      bubbleBunnyEarsOffsetX: 18,
      bubbleBunnyEarsOffsetY: 24,
      bubbleBunnyEarsRotate: 8,
      bubbleBunnyEarsZIndex: -1,
      bubbleMinWidth: 0,
      bubbleMaxWidth: 0,
      bubbleFixedWidth: 0,
      bubbleMinHeight: 0,
      bubbleMaxHeight: 0,
      bubbleFixedHeight: 0,
      avatarSize: 36,
      showAvatar: true,
      showBadges: true,
      animationMs: 320,
      position: 'bottom-up',
      maxMessages: 35,
    },
    layoutConfig: defaultLayout(),
    slotStyleConfig: defaultSlotStyle(),
    animationConfig: {
      enabled: true,
      style: 'bounce',
      targets: {
        avatar:  { durationMs: null, delayMs: 0,  easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0,   translateY: 16, scale: 0.85, blur: 0 },
        author:  { durationMs: null, delayMs: 40, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: -12, translateY: 0,  scale: 0.85, blur: 0 },
        badges:  { durationMs: null, delayMs: 60, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: -8,  translateY: 0,  scale: 0.85, blur: 0 },
        message: { durationMs: null, delayMs: 80, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0,   translateY: 12, scale: 0.85, blur: 0 },
      },
    },
    decorationConfig: emptyDecorations(),
    roleStyleConfig: {
      roles: {
        moderator: { enabled: false, authorColor: '#FF4D9E', authorBorderColor: 'rgba(255, 77, 158, 0.65)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(255, 77, 158, 0.22), rgba(80, 30, 120, 0.78))', messageBorderColor: 'rgba(255, 77, 158, 0.45)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: 'MOD', badgeAfter: null, showAmount: null },
        member: { enabled: false, authorColor: '#A78BFA', authorBorderColor: 'rgba(167, 139, 250, 0.55)', authorBg: null, messageBg: null, messageBorderColor: 'rgba(167, 139, 250, 0.4)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '★', badgeAfter: null, showAmount: null },
        superchat: { enabled: false, authorColor: '#FCD34D', authorBorderColor: 'rgba(252, 211, 77, 0.6)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(252, 211, 77, 0.22), rgba(80, 30, 120, 0.78))', messageBorderColor: 'rgba(252, 211, 77, 0.45)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '✦', badgeAfter: null, showAmount: true },
      },
    },
  },

  // ── Night Sky ──────────────────────────────────────────────────────────────
  {
    id: 'night-sky',
    name: 'Night Sky',
    author: 'built-in',
    version: '1.0.0',
    description: 'Deep navy background with star-white text and a soft aurora glow.',
    category: 'dark',
    tags: ['dark', 'night', 'navy', 'aurora', 'purple'],
    createdAt: '2024-01-01',
    modifiedAt: '2024-01-01',
    customizeConfig: {
      fontFamily: '"Raleway", "Segoe UI", system-ui, sans-serif',
      fontSize: 15,
      textColor: '#E8EAF6',
      authorColor: '#B39DDB',
      bubbleBg: 'rgba(13, 14, 33, 0.85)',
      bubbleRadius: 12,
      bubbleOpacity: 1,
      bubbleBorderWidth: 1,
      bubbleBorderStyle: 'solid',
      bubbleBorderColor: 'rgba(179, 157, 219, 0.3)',
      bubbleBoxShadow: '0 2px 20px rgba(13, 14, 33, 0.6)',
      bubbleGlow: 'drop-shadow(0 0 6px rgba(179, 157, 219, 0.2))',
      bubblePadding: null,
      bubblePaddingX: 14,
      bubblePaddingY: 8,
      bubblePaddingTop: null,
      bubblePaddingRight: null,
      bubblePaddingBottom: null,
      bubblePaddingLeft: null,
      bubbleTextureUrl: null,
      bubbleTextureSize: 'auto',
      bubbleTextureRepeat: 'repeat',
      bubbleTextureOpacity: 1,
      bubbleBunnyEars: false,
      bubbleBunnyEarsWidth: 32,
      bubbleBunnyEarsHeight: 30,
      bubbleBunnyEarsRoundness: 0,
      bubbleBunnyEarsOffsetX: 20,
      bubbleBunnyEarsOffsetY: 28,
      bubbleBunnyEarsRotate: 0,
      bubbleBunnyEarsZIndex: -1,
      bubbleMinWidth: 0,
      bubbleMaxWidth: 0,
      bubbleFixedWidth: 0,
      bubbleMinHeight: 0,
      bubbleMaxHeight: 0,
      bubbleFixedHeight: 0,
      avatarSize: 32,
      showAvatar: true,
      showBadges: true,
      animationMs: 280,
      position: 'bottom-up',
      maxMessages: 40,
    },
    layoutConfig: defaultLayout(),
    slotStyleConfig: defaultSlotStyle(),
    animationConfig: {
      enabled: true,
      style: 'blurZoom',
      targets: {
        avatar:  { durationMs: null, delayMs: 0,  easing: 'ease-out', translateX: 0, translateY: 0, scale: 1.08, blur: 8 },
        author:  { durationMs: null, delayMs: 40, easing: 'ease-out', translateX: 0, translateY: 0, scale: 1.08, blur: 8 },
        badges:  { durationMs: null, delayMs: 60, easing: 'ease-out', translateX: 0, translateY: 0, scale: 1.08, blur: 8 },
        message: { durationMs: null, delayMs: 80, easing: 'ease-out', translateX: 0, translateY: 0, scale: 1.08, blur: 8 },
      },
    },
    decorationConfig: emptyDecorations(),
    roleStyleConfig: {
      roles: {
        moderator: { enabled: false, authorColor: '#EF9A9A', authorBorderColor: 'rgba(239, 154, 154, 0.65)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(239, 154, 154, 0.18), rgba(13, 14, 33, 0.85))', messageBorderColor: 'rgba(239, 154, 154, 0.4)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: 'MOD', badgeAfter: null, showAmount: null },
        member: { enabled: false, authorColor: '#90CAF9', authorBorderColor: 'rgba(144, 202, 249, 0.55)', authorBg: null, messageBg: null, messageBorderColor: 'rgba(144, 202, 249, 0.38)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '★', badgeAfter: null, showAmount: null },
        superchat: { enabled: false, authorColor: '#FFF176', authorBorderColor: 'rgba(255, 241, 118, 0.6)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(255, 241, 118, 0.2), rgba(13, 14, 33, 0.85))', messageBorderColor: 'rgba(255, 241, 118, 0.4)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '✦', badgeAfter: null, showAmount: true },
      },
    },
  },

  // ── Cute ───────────────────────────────────────────────────────────────────
  // Migrated from the former Quick Style preset system.
  {
    id: 'cute',
    name: 'Cute',
    author: 'built-in',
    version: '1.0.0',
    description: 'Warm pink bubbles with round edges and bunny ears — a cosy, kawaii look.',
    category: 'cute',
    tags: ['cute', 'pink', 'kawaii', 'bunny'],
    createdAt: '2024-01-01',
    modifiedAt: '2024-01-01',
    customizeConfig: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: 16,
      textColor: '#3A2233',
      authorColor: '#FF5FA8',
      bubbleBg: 'rgba(255, 235, 246, 0.92)',
      bubbleRadius: 22,
      bubbleOpacity: 1,
      bubbleBorderWidth: null,
      bubbleBorderStyle: null,
      bubbleBorderColor: null,
      bubbleBoxShadow: '0 4px 14px rgba(255, 140, 200, 0.25)',
      bubbleGlow: null,
      bubblePadding: null,
      bubblePaddingX: null,
      bubblePaddingY: null,
      bubblePaddingTop: null,
      bubblePaddingRight: null,
      bubblePaddingBottom: null,
      bubblePaddingLeft: null,
      bubbleTextureUrl: null,
      bubbleTextureSize: 'auto',
      bubbleTextureRepeat: 'repeat',
      bubbleTextureOpacity: 1,
      bubbleBunnyEars: true,
      bubbleBunnyEarsWidth: 32,
      bubbleBunnyEarsHeight: 30,
      bubbleBunnyEarsRoundness: 0,
      bubbleBunnyEarsOffsetX: 20,
      bubbleBunnyEarsOffsetY: 28,
      bubbleBunnyEarsRotate: 0,
      bubbleBunnyEarsZIndex: -1,
      bubbleMinWidth: 0,
      bubbleMaxWidth: 0,
      bubbleFixedWidth: 0,
      bubbleMinHeight: 0,
      bubbleMaxHeight: 0,
      bubbleFixedHeight: 0,
      avatarSize: 32,
      showAvatar: true,
      showBadges: true,
      animationMs: 220,
      position: 'bottom-up',
      maxMessages: 40,
    },
    layoutConfig: defaultLayout(),
    slotStyleConfig: defaultSlotStyle(),
    animationConfig: defaultAnimation(),
    decorationConfig: emptyDecorations(),
    roleStyleConfig: {
      roles: {
        moderator: { enabled: false, authorColor: '#E91E8C', authorBorderColor: 'rgba(233, 30, 140, 0.6)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(233, 30, 140, 0.15), rgba(255, 235, 246, 0.85))', messageBorderColor: 'rgba(233, 30, 140, 0.35)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: 'MOD', badgeAfter: null, showAmount: null },
        member: { enabled: false, authorColor: '#9C5FA8', authorBorderColor: 'rgba(156, 95, 168, 0.5)', authorBg: null, messageBg: null, messageBorderColor: 'rgba(156, 95, 168, 0.35)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '★', badgeAfter: null, showAmount: null },
        superchat: { enabled: false, authorColor: '#F57F17', authorBorderColor: 'rgba(245, 127, 23, 0.55)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(245, 127, 23, 0.18), rgba(255, 235, 246, 0.85))', messageBorderColor: 'rgba(245, 127, 23, 0.4)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '✦', badgeAfter: null, showAmount: true },
      },
    },
  },

  // ── Dreamcore ──────────────────────────────────────────────────────────────
  // Migrated from the former Quick Style preset system.
  {
    id: 'dreamcore',
    name: 'Dreamcore',
    author: 'built-in',
    version: '1.0.0',
    description: 'Deep purple semi-transparent bubble with a dashed lilac border and bunny ears.',
    category: 'colorful',
    tags: ['dream', 'purple', 'pastel', 'bunny'],
    createdAt: '2024-01-01',
    modifiedAt: '2024-01-01',
    customizeConfig: {
      fontFamily: '"Space Grotesk", system-ui, sans-serif',
      fontSize: 16,
      textColor: '#F1E9FF',
      authorColor: '#C7A7FF',
      bubbleBg: 'rgba(88, 61, 138, 0.55)',
      bubbleRadius: 26,
      bubbleOpacity: 1,
      bubbleBorderWidth: 1,
      bubbleBorderStyle: 'dashed',
      bubbleBorderColor: '#C7A7FF',
      bubbleBoxShadow: '0 8px 24px rgba(120, 80, 200, 0.35)',
      bubbleGlow: null,
      bubblePadding: null,
      bubblePaddingX: null,
      bubblePaddingY: null,
      bubblePaddingTop: null,
      bubblePaddingRight: null,
      bubblePaddingBottom: null,
      bubblePaddingLeft: null,
      bubbleTextureUrl: null,
      bubbleTextureSize: 'auto',
      bubbleTextureRepeat: 'repeat',
      bubbleTextureOpacity: 1,
      bubbleBunnyEars: true,
      bubbleBunnyEarsWidth: 32,
      bubbleBunnyEarsHeight: 30,
      bubbleBunnyEarsRoundness: 0,
      bubbleBunnyEarsOffsetX: 20,
      bubbleBunnyEarsOffsetY: 28,
      bubbleBunnyEarsRotate: 0,
      bubbleBunnyEarsZIndex: -1,
      bubbleMinWidth: 0,
      bubbleMaxWidth: 0,
      bubbleFixedWidth: 0,
      bubbleMinHeight: 0,
      bubbleMaxHeight: 0,
      bubbleFixedHeight: 0,
      avatarSize: 32,
      showAvatar: true,
      showBadges: true,
      animationMs: 280,
      position: 'bottom-up',
      maxMessages: 40,
    },
    layoutConfig: defaultLayout(),
    slotStyleConfig: defaultSlotStyle(),
    animationConfig: {
      enabled: true,
      style: 'blurZoom',
      targets: {
        avatar:  { durationMs: null, delayMs: 0,  easing: 'ease-out', translateX: 0, translateY: 0, scale: 1.08, blur: 8 },
        author:  { durationMs: null, delayMs: 40, easing: 'ease-out', translateX: 0, translateY: 0, scale: 1.08, blur: 8 },
        badges:  { durationMs: null, delayMs: 60, easing: 'ease-out', translateX: 0, translateY: 0, scale: 1.08, blur: 8 },
        message: { durationMs: null, delayMs: 80, easing: 'ease-out', translateX: 0, translateY: 0, scale: 1.08, blur: 8 },
      },
    },
    decorationConfig: emptyDecorations(),
    roleStyleConfig: {
      roles: {
        moderator: { enabled: false, authorColor: '#FF80AB', authorBorderColor: 'rgba(255, 128, 171, 0.65)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(255, 128, 171, 0.2), rgba(88, 61, 138, 0.55))', messageBorderColor: 'rgba(255, 128, 171, 0.45)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: 'MOD', badgeAfter: null, showAmount: null },
        member: { enabled: false, authorColor: '#82B1FF', authorBorderColor: 'rgba(130, 177, 255, 0.55)', authorBg: null, messageBg: null, messageBorderColor: 'rgba(130, 177, 255, 0.38)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '★', badgeAfter: null, showAmount: null },
        superchat: { enabled: false, authorColor: '#FFD740', authorBorderColor: 'rgba(255, 215, 64, 0.6)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(255, 215, 64, 0.22), rgba(88, 61, 138, 0.55))', messageBorderColor: 'rgba(255, 215, 64, 0.4)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '✦', badgeAfter: null, showAmount: true },
      },
    },
  },

  // ── Retro ──────────────────────────────────────────────────────────────────
  // Migrated from the former Quick Style preset system.
  {
    id: 'retro',
    name: 'Retro',
    author: 'built-in',
    version: '1.0.0',
    description: 'Warm parchment bubbles with a monospace font and hard ink border — vintage terminal vibes.',
    category: 'dark',
    tags: ['retro', 'monospace', 'vintage', 'light'],
    createdAt: '2024-01-01',
    modifiedAt: '2024-01-01',
    customizeConfig: {
      fontFamily: 'ui-monospace, "JetBrains Mono", monospace',
      fontSize: 14,
      textColor: '#2B1B0E',
      authorColor: '#B8410C',
      bubbleBg: 'rgba(245, 224, 178, 0.95)',
      bubbleRadius: 4,
      bubbleOpacity: 1,
      bubbleBorderWidth: 2,
      bubbleBorderStyle: 'solid',
      bubbleBorderColor: '#2B1B0E',
      bubbleBoxShadow: null,
      bubbleGlow: null,
      bubblePadding: null,
      bubblePaddingX: null,
      bubblePaddingY: null,
      bubblePaddingTop: null,
      bubblePaddingRight: null,
      bubblePaddingBottom: null,
      bubblePaddingLeft: null,
      bubbleTextureUrl: null,
      bubbleTextureSize: 'auto',
      bubbleTextureRepeat: 'repeat',
      bubbleTextureOpacity: 1,
      bubbleBunnyEars: false,
      bubbleBunnyEarsWidth: 32,
      bubbleBunnyEarsHeight: 30,
      bubbleBunnyEarsRoundness: 0,
      bubbleBunnyEarsOffsetX: 20,
      bubbleBunnyEarsOffsetY: 28,
      bubbleBunnyEarsRotate: 0,
      bubbleBunnyEarsZIndex: -1,
      bubbleMinWidth: 0,
      bubbleMaxWidth: 0,
      bubbleFixedWidth: 0,
      bubbleMinHeight: 0,
      bubbleMaxHeight: 0,
      bubbleFixedHeight: 0,
      avatarSize: 32,
      showAvatar: true,
      showBadges: true,
      animationMs: 200,
      position: 'bottom-up',
      maxMessages: 40,
    },
    layoutConfig: defaultLayout(),
    slotStyleConfig: defaultSlotStyle(),
    animationConfig: defaultAnimation(),
    decorationConfig: emptyDecorations(),
    roleStyleConfig: {
      roles: {
        moderator: { enabled: false, authorColor: '#8B0000', authorBorderColor: 'rgba(139, 0, 0, 0.7)', authorBg: null, messageBg: 'rgba(255, 220, 220, 0.6)', messageBorderColor: 'rgba(139, 0, 0, 0.45)', messageTextColor: '#2B1B0E', rowBg: null, rowBorderColor: null, badgeBefore: 'MOD', badgeAfter: null, showAmount: null },
        member: { enabled: false, authorColor: '#1A4D8C', authorBorderColor: 'rgba(26, 77, 140, 0.55)', authorBg: null, messageBg: null, messageBorderColor: 'rgba(26, 77, 140, 0.4)', messageTextColor: '#2B1B0E', rowBg: null, rowBorderColor: null, badgeBefore: '★', badgeAfter: null, showAmount: null },
        superchat: { enabled: false, authorColor: '#7B4A00', authorBorderColor: 'rgba(123, 74, 0, 0.6)', authorBg: null, messageBg: 'rgba(255, 240, 190, 0.8)', messageBorderColor: 'rgba(123, 74, 0, 0.4)', messageTextColor: '#2B1B0E', rowBg: null, rowBorderColor: null, badgeBefore: '✦', badgeAfter: null, showAmount: true },
      },
    },
  },

  // ── Neon ───────────────────────────────────────────────────────────────────
  // Migrated from the former Quick Style preset system.
  // Distinct from cyber-neon: teal-green accent (#35E6B0) vs cyan (#00E5FF),
  // stronger double drop-shadow glow, and round radius (10px) vs sharp (4px).
  {
    id: 'neon',
    name: 'Neon',
    author: 'built-in',
    version: '1.0.0',
    description: 'Dark terminal bubble with teal-green neon border and double drop-shadow glow.',
    category: 'gaming',
    tags: ['neon', 'glow', 'monospace', 'teal', 'gaming'],
    createdAt: '2024-01-01',
    modifiedAt: '2024-01-01',
    customizeConfig: {
      fontFamily: 'ui-monospace, "JetBrains Mono", monospace',
      fontSize: 14,
      textColor: '#EAECEF',
      authorColor: '#35E6B0',
      bubbleBg: 'rgba(14, 16, 19, 0.85)',
      bubbleRadius: 10,
      bubbleOpacity: 1,
      bubbleBorderWidth: 2,
      bubbleBorderStyle: 'solid',
      bubbleBorderColor: '#35E6B0',
      bubbleBoxShadow: '0 0 18px rgba(53, 230, 176, 0.55)',
      bubbleGlow: 'drop-shadow(0 0 6px rgba(53, 230, 176, 0.85)) drop-shadow(0 0 18px rgba(53, 230, 176, 0.55))',
      bubblePadding: null,
      bubblePaddingX: 12,
      bubblePaddingY: 6,
      bubblePaddingTop: null,
      bubblePaddingRight: null,
      bubblePaddingBottom: null,
      bubblePaddingLeft: null,
      bubbleTextureUrl: null,
      bubbleTextureSize: 'auto',
      bubbleTextureRepeat: 'repeat',
      bubbleTextureOpacity: 1,
      bubbleBunnyEars: false,
      bubbleBunnyEarsWidth: 32,
      bubbleBunnyEarsHeight: 30,
      bubbleBunnyEarsRoundness: 0,
      bubbleBunnyEarsOffsetX: 20,
      bubbleBunnyEarsOffsetY: 28,
      bubbleBunnyEarsRotate: 0,
      bubbleBunnyEarsZIndex: -1,
      bubbleMinWidth: 0,
      bubbleMaxWidth: 0,
      bubbleFixedWidth: 0,
      bubbleMinHeight: 0,
      bubbleMaxHeight: 0,
      bubbleFixedHeight: 0,
      avatarSize: 28,
      showAvatar: true,
      showBadges: true,
      animationMs: 180,
      position: 'bottom-up',
      maxMessages: 40,
    },
    layoutConfig: defaultLayout(),
    slotStyleConfig: defaultSlotStyle(),
    animationConfig: {
      enabled: true,
      style: 'slideStrong',
      targets: {
        avatar:  { durationMs: null, delayMs: 0,  easing: 'cubic-bezier(0.16, 1, 0.3, 1)', translateX: 0,   translateY: 40, scale: 1, blur: 0 },
        author:  { durationMs: null, delayMs: 40, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', translateX: -30, translateY: 0,  scale: 1, blur: 0 },
        badges:  { durationMs: null, delayMs: 60, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', translateX: -20, translateY: 0,  scale: 1, blur: 0 },
        message: { durationMs: null, delayMs: 80, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', translateX: 0,   translateY: 30, scale: 1, blur: 0 },
      },
    },
    decorationConfig: emptyDecorations(),
    roleStyleConfig: {
      roles: {
        moderator: { enabled: false, authorColor: '#FF4081', authorBorderColor: 'rgba(255, 64, 129, 0.7)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(255, 64, 129, 0.18), rgba(14, 16, 19, 0.85))', messageBorderColor: 'rgba(255, 64, 129, 0.45)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: 'MOD', badgeAfter: null, showAmount: null },
        member: { enabled: false, authorColor: '#69F0AE', authorBorderColor: 'rgba(105, 240, 174, 0.55)', authorBg: null, messageBg: null, messageBorderColor: 'rgba(105, 240, 174, 0.4)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '★', badgeAfter: null, showAmount: null },
        superchat: { enabled: false, authorColor: '#FFE57F', authorBorderColor: 'rgba(255, 229, 127, 0.6)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(255, 229, 127, 0.22), rgba(14, 16, 19, 0.85))', messageBorderColor: 'rgba(255, 229, 127, 0.4)', messageTextColor: null, rowBg: 'linear-gradient(135deg, rgba(255, 229, 127, 0.15), rgba(14, 16, 19, 0.85))', rowBorderColor: 'rgba(255, 229, 127, 0.4)', badgeBefore: '✦', badgeAfter: null, showAmount: true },
      },
    },
  },

  // ── Maid ───────────────────────────────────────────────────────────────────
  {
    id: 'maid',
    name: 'Maid',
    author: 'built-in',
    version: '1.0.0',
    description: 'Maid café style — crisp white bubble, black lace trim, and a cherry-red bow accent.',
    category: 'cute',
    tags: ['maid', 'cute', 'white', 'black', 'red', 'lolita'],
    createdAt: '2026-07-13',
    modifiedAt: '2026-07-13',
    customizeConfig: {
      fontFamily: '"Poppins", "Quicksand", system-ui, sans-serif',
      fontSize: 15,
      textColor: '#3A2E2E',
      authorColor: '#C81E3A',
      bubbleBg: 'rgba(255, 250, 250, 0.92)',
      bubbleRadius: 16,
      bubbleOpacity: 1,
      bubbleBorderWidth: 2,
      bubbleBorderStyle: 'solid',
      bubbleBorderColor: 'rgba(30, 27, 27, 0.85)',
      bubbleBoxShadow: '0 3px 14px rgba(0, 0, 0, 0.16)',
      bubbleGlow: null,
      bubblePadding: null,
      bubblePaddingX: 14,
      bubblePaddingY: 8,
      bubblePaddingTop: null,
      bubblePaddingRight: null,
      bubblePaddingBottom: null,
      bubblePaddingLeft: null,
      bubbleTextureUrl: null,
      bubbleTextureSize: 'auto',
      bubbleTextureRepeat: 'repeat',
      bubbleTextureOpacity: 1,
      bubbleBunnyEars: true,
      bubbleBunnyEarsWidth: 30,
      bubbleBunnyEarsHeight: 28,
      bubbleBunnyEarsRoundness: 6,
      bubbleBunnyEarsOffsetX: 18,
      bubbleBunnyEarsOffsetY: 26,
      bubbleBunnyEarsRotate: 0,
      bubbleBunnyEarsZIndex: -1,
      bubbleMinWidth: 0,
      bubbleMaxWidth: 0,
      bubbleFixedWidth: 0,
      bubbleMinHeight: 0,
      bubbleMaxHeight: 0,
      bubbleFixedHeight: 0,
      avatarSize: 32,
      showAvatar: true,
      showBadges: true,
      animationMs: 260,
      position: 'bottom-up',
      maxMessages: 35,
    },
    layoutConfig: defaultLayout(),
    slotStyleConfig: defaultSlotStyle(),
    animationConfig: {
      enabled: true,
      style: 'bounce',
      targets: {
        avatar:  { durationMs: null, delayMs: 0,  easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0,   translateY: 14, scale: 0.9, blur: 0 },
        author:  { durationMs: null, delayMs: 40, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: -10, translateY: 0,  scale: 0.9, blur: 0 },
        badges:  { durationMs: null, delayMs: 60, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: -8,  translateY: 0,  scale: 0.9, blur: 0 },
        message: { durationMs: null, delayMs: 80, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)', translateX: 0,   translateY: 10, scale: 0.9, blur: 0 },
      },
    },
    decorationConfig: emptyDecorations(),
    roleStyleConfig: {
      roles: {
        moderator: { enabled: false, authorColor: '#1E1B1B', authorBorderColor: 'rgba(30, 27, 27, 0.7)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(30, 27, 27, 0.12), rgba(255, 250, 250, 0.92))', messageBorderColor: 'rgba(30, 27, 27, 0.4)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: 'MOD', badgeAfter: null, showAmount: null },
        member: { enabled: false, authorColor: '#C81E3A', authorBorderColor: 'rgba(200, 30, 58, 0.5)', authorBg: null, messageBg: null, messageBorderColor: 'rgba(200, 30, 58, 0.35)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '🎀', badgeAfter: null, showAmount: null },
        superchat: { enabled: false, authorColor: '#D4A017', authorBorderColor: 'rgba(212, 160, 23, 0.55)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(212, 160, 23, 0.2), rgba(255, 250, 250, 0.92))', messageBorderColor: 'rgba(212, 160, 23, 0.4)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '✦', badgeAfter: null, showAmount: true },
      },
    },
  },

  // ── Cà Phê ───────────────────────────────────────────────────────────────────
  {
    id: 'ca-phe',
    name: 'Cà Phê',
    author: 'built-in',
    version: '1.0.0',
    description: 'Warm coffee-shop tones — cream bubble, espresso-brown border, cinnamon accents.',
    category: 'cozy',
    tags: ['coffee', 'cozy', 'brown', 'cream', 'warm'],
    createdAt: '2026-07-13',
    modifiedAt: '2026-07-13',
    customizeConfig: {
      fontFamily: '"Nunito", "Merriweather", system-ui, serif',
      fontSize: 15,
      textColor: '#4B3324',
      authorColor: '#8B4513',
      bubbleBg: 'rgba(245, 232, 216, 0.88)',
      bubbleRadius: 14,
      bubbleOpacity: 1,
      bubbleBorderWidth: 1,
      bubbleBorderStyle: 'solid',
      bubbleBorderColor: 'rgba(93, 64, 55, 0.4)',
      bubbleBoxShadow: '0 3px 12px rgba(75, 51, 36, 0.18)',
      bubbleGlow: null,
      bubblePadding: null,
      bubblePaddingX: 14,
      bubblePaddingY: 8,
      bubblePaddingTop: null,
      bubblePaddingRight: null,
      bubblePaddingBottom: null,
      bubblePaddingLeft: null,
      bubbleTextureUrl: null,
      bubbleTextureSize: 'auto',
      bubbleTextureRepeat: 'repeat',
      bubbleTextureOpacity: 1,
      bubbleBunnyEars: false,
      bubbleBunnyEarsWidth: 32,
      bubbleBunnyEarsHeight: 30,
      bubbleBunnyEarsRoundness: 0,
      bubbleBunnyEarsOffsetX: 20,
      bubbleBunnyEarsOffsetY: 28,
      bubbleBunnyEarsRotate: 0,
      bubbleBunnyEarsZIndex: -1,
      bubbleMinWidth: 0,
      bubbleMaxWidth: 0,
      bubbleFixedWidth: 0,
      bubbleMinHeight: 0,
      bubbleMaxHeight: 0,
      bubbleFixedHeight: 0,
      avatarSize: 30,
      showAvatar: true,
      showBadges: true,
      animationMs: 260,
      position: 'bottom-up',
      maxMessages: 35,
    },
    layoutConfig: defaultLayout(),
    slotStyleConfig: defaultSlotStyle(),
    animationConfig: {
      enabled: true,
      style: 'slide',
      targets: {
        avatar:  { durationMs: null, delayMs: 0,  easing: 'ease-out', translateX: 0,  translateY: 10, scale: 1, blur: 0 },
        author:  { durationMs: null, delayMs: 40, easing: 'ease-out', translateX: -8, translateY: 0,  scale: 1, blur: 0 },
        badges:  { durationMs: null, delayMs: 60, easing: 'ease-out', translateX: -6, translateY: 0,  scale: 1, blur: 0 },
        message: { durationMs: null, delayMs: 80, easing: 'ease-out', translateX: 0,  translateY: 8,  scale: 1, blur: 0 },
      },
    },
    decorationConfig: emptyDecorations(),
    roleStyleConfig: {
      roles: {
        moderator: { enabled: false, authorColor: '#6F4E37', authorBorderColor: 'rgba(111, 78, 55, 0.65)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(111, 78, 55, 0.2), rgba(245, 232, 216, 0.88))', messageBorderColor: 'rgba(111, 78, 55, 0.4)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: 'MOD', badgeAfter: null, showAmount: null },
        member: { enabled: false, authorColor: '#A0522D', authorBorderColor: 'rgba(160, 82, 45, 0.5)', authorBg: null, messageBg: null, messageBorderColor: 'rgba(160, 82, 45, 0.35)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '☕', badgeAfter: null, showAmount: null },
        superchat: { enabled: false, authorColor: '#C68A3D', authorBorderColor: 'rgba(198, 138, 61, 0.55)', authorBg: null, messageBg: 'linear-gradient(135deg, rgba(198, 138, 61, 0.22), rgba(245, 232, 216, 0.88))', messageBorderColor: 'rgba(198, 138, 61, 0.4)', messageTextColor: null, rowBg: null, rowBorderColor: null, badgeBefore: '✦', badgeAfter: null, showAmount: true },
      },
    },
  },

];

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

module.exports = { BUILTIN_THEMES };